lblod/ember-rdfa-editor-lblod-plugins

- addon/plugins/article-structure-plugin/commands/insert-structure.ts
- addon/plugins/article-structure-plugin/commands/move-selected-structure.ts
- addon/plugins/article-structure-plugin/commands/wrap-structure-content.ts
- addon/plugins/article-structure-plugin/index.ts
- addon/plugins/article-structure-plugin/structures/article-paragraph.ts
- addon/plugins/article-structure-plugin/structures/article.ts
- addon/plugins/article-structure-plugin/structures/chapter.ts
- addon/plugins/article-structure-plugin/structures/section.ts
- addon/plugins/article-structure-plugin/structures/subsection.ts
- addon/plugins/article-structure-plugin/structures/title.ts
Until now, each structure-spec had a context property which determined in which node-types it could be inserted. This context property is not really necessary as this check can also be completely performed using the prosemirror `canReplaceWith` method. This PR removes the redundant context property.
> Remove redundant context from article-structure plugin

- addon/plugins/article-structure-plugin/commands/insert-structure.ts
- addon/plugins/article-structure-plugin/structures/structure-header.ts
- addon/plugins/article-structure-plugin/utils/structure.ts
When inserting a structure and it cant be inserted into the current container, the insert-command now looks forward into the document to find a container it can be inserted in and inserts it at the end of this container.
> Update insert-structure command so it looks forward for the next best position to insert

- addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
- addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
- addon/plugins/article-structure-plugin/commands/insert-structure.ts
- addon/plugins/standard-template-plugin/utils/nodes.ts
This PR does two things:
- it uses the new decision articles and the insert-structure command from the article-structure plugin
- it drops the dependency from the datastore.
> Roadsign regulation plugin rework

- addon/components/citation-plugin/citation-card.hbs
- addon/components/citation-plugin/citation-insert.hbs
- addon/components/citation-plugin/citation-insert.ts
- addon/components/citation-plugin/citations/search-modal.hbs
- addon/components/citation-plugin/citations/search-modal.ts
The legislation type of the modal is initialized in its constructor. The issue is: this constructor is not called each time the modal component is opened, as the modal already exists, its just hidden.
I see two solutions:
- We recreate the modal each time it is opened (which is how this PR does it) => the constructor is run every time it is opened, the most simple solution
- We initialize the `legislationType` in a modifier, e.g. `did-insert`.
This PR solves https://binnenland.atlassian.net/browse/GN-3952?atlOrigin=eyJpIjoiYjE0NWMxMzQzM2ExNGExYzhjYzRhZDY5NzM1NDBkYmIiLCJwIjoiaiJ9.
> Ensure that the citation type is preserved between the sidebar card and the modal

- addon/plugins/article-structure-plugin/structures/article-paragraph.ts
- addon/plugins/article-structure-plugin/structures/article.ts
- addon/plugins/article-structure-plugin/utils/structure.ts
This PR ensures that article paragraphs following the old format are also parsed correctly and converted to the new format.
> Add backwards compatible parsing rule to article_paragraph

- addon/plugins/citation-plugin/index.ts
- addon/plugins/citation-plugin/nodes/motivation.ts
- addon/utils/changed-descendants.ts
- addon/utils/constants.ts
- tests/dummy/app/controllers/besluit-sample.ts
Adds a new way of configuring the citation plugin activation ranges, by specifiying a function that returns a set of nodetypes in which the plugin should trigger. This calculation is efficient thanks to the use of a `changedDescendants` utility as demonstrated in the [prosemirror tables plugin](https://github.com/ProseMirror/prosemirror-tables/blob/8ec1e96ae994c1585b07b1ca9dc3292f63e868e0/src/fixtables.ts#L24), found [in this discussion thread](https://discuss.prosemirror.net/t/efficiently-finding-changed-nodes/4280)
The old way of directly specifying the ranges is still supported, but no longer provides the datastore as a second argument, which is the reason for the `breaking` label. This is actually just a more sensible design anyway, removing the implicit dependency of the citation …
> feat(citation): make citation plugin datastore-independent

- addon/plugins/article-structure-plugin/structures/article.ts
- addon/plugins/article-structure-plugin/structures/chapter.ts
- addon/plugins/article-structure-plugin/structures/section.ts
- addon/plugins/article-structure-plugin/structures/subsection.ts
- addon/plugins/article-structure-plugin/structures/title.ts
- addon/plugins/roadsign-regulation-plugin/nodes.ts
- addon/plugins/standard-template-plugin/utils/nodes.ts
- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
This PR does the following three things:
- Replace `paragraph` by `block` in content specifiers of node-specs, so they allow for more diverse content
- Remove `block` group from chapter and title nodes, and add chapter and title as possible nodes to content of `doc` in regulatory-statement-sample.
- Add a missing `contentElement` specifier to the `roadsign_regulation` node parsing rule.
> Replace paragraphs by block in content specifiers and fix roadsign-regulation parsing rule

- app/styles/variable-plugin.scss
This PR ensures that words are broken up when they are about to overflow a variable container.
> Enable word-break as break-all on variable contenteditable

- addon/plugins/article-structure-plugin/commands/insert-structure.ts
- addon/plugins/article-structure-plugin/commands/move-selected-structure.ts
- addon/plugins/article-structure-plugin/index.ts
- addon/plugins/standard-template-plugin/utils/nodes.ts
This PR includes two changes:
- the insert-structure command now also looks backwards for a container to insert into if no other insertion containers are found
- addition of the optional `limitTo` property to a structure-spec: this property defines whether the insertion range of a structure type should be constrained to another node-type. E.g. the insertion of `besluit-article` nodes should be constrained to the current besluit. You don't want the possibility to occur that when inserting a `besluit-article` it is inserted in another besluit than the current one.
> Article-structure-plugin: structure insertion improvements

- addon/plugins/standard-template-plugin/utils/nodes.ts
- make the important nodes defining
- make other heading levels also parse as a title, which means the classic decision template works as expected (it has an h5 instead of an h4)
I didn't change the toDom (so in the end it will always be an h4) because the insert-title command would insert an h4 anyway. We can address this more seriously when we add the heading selector feature.
> Improve behavior of decision nodes

- addon/components/standard-template-plugin/template-provider.ts
Make inserting standard templates less awkward by replacing the paragraph you're in (if you're in one) instead of inserting it after (which leaves you with a newline where you don't expect it)
> fix(template): improve template insertion behavior

- addon/components/besluit-type-plugin/toolbar-dropdown.ts
This goes in the hall of fame of most annoying bugs I've ever had to track down
> fix(decision-type): don't remove the type we just added if it happens to be the same as the old one

- addon/plugins/article-structure-plugin/structures/article-paragraph.ts
- addon/plugins/article-structure-plugin/structures/article.ts
- addon/plugins/article-structure-plugin/structures/structure-header.ts
- addon/plugins/article-structure-plugin/utils/structure.ts
- addon/plugins/standard-template-plugin/utils/nodes.ts
This PR introduces the addition of the `defining` and `isolating` attributes on the content and headers of article-structures.
This ensures that you cant backspace out of these nodes and that they are preserved when pasting content inside of them. This solves a lot of weird backspace collapsing bugs, as seen in https://binnenland.atlassian.net/browse/GN-3994?atlOrigin=eyJpIjoiNzQ1ZDM4YThlZTE5NGQ0M2JkZjVjZGU2N2NkODY0NjciLCJwIjoiaiJ9.
> Make headers and content nodes of structures isolating and defining

- addon/plugins/standard-template-plugin/utils/nodes.ts
- package.json
Adds `canSplit: false` to besluit related nodes.
> Prevent splitting of besluit related nodes

- addon/components/rdfa-date-plugin/card.ts
- addon/plugins/rdfa-date-plugin/utils.ts
This PR fixes two issues:
- The check whether a date-format contains time-related characters now ignores text between quotation marks
- When adding/removing time from a date, `xsd:date` is used when it does not contain a time and `xsd:dateTime` is used when it does contain a time and not the other way around.
> Fix: correcltly set the date type as xsd:date or xsd:dateTime based on the date content

- addon/plugins/besluit-plugin/commands/insert-title.ts
- addon/plugins/citation-plugin/utils/cited-text.ts
- addon/plugins/standard-template-plugin/utils/nodes.ts
This PR ensures that an __rdfaId is already added to title and article nodes as well as citation marks when creating them manually and to ensure these are not added after a reload. Solves https://binnenland.atlassian.net/browse/GN-4008?atlOrigin=eyJpIjoiODk1NmFlYmJjOGZhNDlmMTk3ODk5NDA1ZTE3ZWNjZmQiLCJwIjoiaiJ9.
Note: this is a temporary solution, ideally we should be able to add default generation functions to attributes such as __rdfaId.
> Add the __rdfaId when manually creating decisions titles, decision articles or citations

- addon/plugins/citation-plugin/index.ts
- addon/plugins/citation-plugin/utils/process-match.ts
- highlights were calculated only on changed sections, but the non-changed highlights were thrown away in the process
- "bijzondere wet" was not triggering correctly
- the regex to strip away spaces used quotes instead of backticks, meaning it matched literally on each of the characters in `${UNBREAKABLE_SPACE}`
> fix citation highlights not triggering correctly in various situations

- CHANGELOG.md
- addon/plugins/variable-plugin/nodes.ts
For newly created codelists in MOW, the `resource` attribute is used to indicate the codelist URI, but in older codelists, the `content` attribute was used. This is a hotfix which ensures that possible `content` attributes are checked in order to extract the codelist URI.
Solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-4095.
> Hotfix: use content attribute as a fallback to extract the codelist URI

- addon/components/article-structure-plugin/structure-card.hbs
- addon/components/article-structure-plugin/structure-card.ts
- addon/plugins/article-structure-plugin/index.ts
- addon/plugins/article-structure-plugin/structures/article-paragraph.ts
Per Bart request, it doesn't really make sense to unwrap an article paragraph. So I added this new option that allows you to define a structure without the unwrap behaviour
> Added a new option to the structures to not support unwrap and made the article paragraphs the first structure to use this option

- CHANGELOG.md
- addon/components/citation-plugin/citation-insert.ts
- tests/dummy/app/templates/besluit-sample.hbs
This PR ensures the citation-plugin functionality can be used without the citation prosemirror-plugin and regex-based autocomplete feature.
In order to integrate the citation-plugin without the autocomplete functionality, only the `CitationPlugin::CitationInsert` needs to be used.
> Remove unused code and plugin dependency from citation-insert component

- CHANGELOG.md
- addon/plugins/standard-template-plugin/utils/nodes.ts
One of the specs was simply wrong: the article_section of a decision should not have the decision type. In certain scenarios, this node was created by default (without the type), which caused a weird state in combination with the besluit_article_content spec, causing the document state to always change when serializing/deserializing
fix: added a context specifier for both nodes so they only parse in the exact cases they are expected to
solves (or helps with solving) https://binnenland.atlassian.net/browse/GN-4169
> fix(decision-nodes): make nodespecs unambiguous

- CHANGELOG.md
- README.md
- addon/components/citation-plugin/citation-insert.ts
cause was a misunderstanding of how `findParentNodeOfType` works. Turns out it never visits the root node.
also updated docs with examples of how to activate the plugin in the entire document
> fix(citation): make plugin trigger correctly when `doc` is passed as an allowed nodeType

- CHANGELOG.md
- addon/components/rdfa-date-plugin/card.hbs
- addon/plugins/rdfa-date-plugin/index.ts
- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
Saska said that putting the formats in the labels was going to be more clear to the end user
> Change date labels based on designer feedback

- CHANGELOG.md
- package-lock.json
- package.json
- Bump `@lblod/ember-rdfa-editor` package to fix annotation not present for some structures
https://binnenland.atlassian.net/browse/GN-4311
> GN-4311: Bump `@lblod/ember-rdfa-editor` package

- CHANGELOG.md
- addon/plugins/variable-plugin/utils/fetch-data.ts
connected PR: [frontend-reglementaire-bijlage #81](https://github.com/lblod/frontend-reglementaire-bijlage/pull/81)
Also fetches labels of codelist options (if they exist) and show them (if they exist).
Note: this change is not yet done for MOW. However, this update works with options with no labels too. So this is not breaking and can be merged before that fix.
> [Variables/codelists] support labels in codelists

- CHANGELOG.md
- addon/plugins/table-of-contents-plugin/nodes/table-of-contents.ts
This PR is a quick fix in order to ensure the static version of the table-of-contents node is displayed in dutch instead of english. A more extensive fix with the concept of a 'document language' may follow later.
Jira: https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4/backlog?issueLimit=100&atlOrigin=eyJpIjoiYTQxYmFlMDE5NzVhNDQxY2FmOTAwYTQzOWQ3MjliNTYiLCJwIjoiaiJ9
Insert a table-of-contents node and check if the exported version is titled 'Inhoudstafel' instead of 'Table of Contents'
> GN-4365: use dutch instead of english for static version of table-of-contents node

- CHANGELOG.md
- addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
This PR fixes the issue with filtering roadsign-regulations by their code. The main issue was the endpoint not being passed to the `searchCode task`.
Jira: https://binnenland.atlassian.net/browse/GN-4351?atlOrigin=eyJpIjoiYjA4YjRkOTcyYjIzNDFhNWJmNjFiMzhjMGE2OTY3YzAiLCJwIjoiaiJ9
- Create a decision with type `Reglementen en verordeningen`
- Open the insert-mobility-measure modal
- Type a valid code in the code filter dropdown
Note: you will notice a lot of other errors in the console popping up (failed requests). These are out of scope for this PR, but I'm now working on a small refactor of the components which should fix these issues.
> GN-4351: fix roadsign-regulation code filtering

- CHANGELOG.md
- addon/plugins/variable-plugin/nodes.ts
Reworked the variable plugin to show the placeholder nummer when no number was inserted
[jira ticket](https://binnenland.atlassian.net/browse/GN-4404?atlOrigin=eyJpIjoiZTA0YmM3YTAwNWNhNDA5YTlmZjJiMTNlNTI4ZDEyYzYiLCJwIjoiaiJ9)
none
Insert a number variable, don't fill it and then click on the show html export button, you should see nummer instead of nothing 
Currently only nummer gets written, which is correct for now, but it has to change when the document language gets implemented in https://github.com/lblod/ember-rdfa-editor/pull/872
> GN-4404: Made the number variable also show placeholders

- CHANGELOG.md
- package-lock.json
- package.json
- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
- tsconfig.json
bumps editor to [4.0.0](https://github.com/lblod/ember-rdfa-editor/releases/tag/v4.0.0)
fixes the `dompurify` type error:
it was due to a misconfiguration of the `tsconfig` file. That file was routing `ember-rdfa-editor` imports to the `/addon` directory, which was done for development with the npm link, but that causes type resolution issues and is not recommended.
So for now when developing in that scenario, we simply have to run `ember ts:precompile` manually when we change the public editor types.
> chore(deps): bump editor to 4.0.0

- CHANGELOG.md
- package-lock.json
- package.json
- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
revert the dev dependency on the editor back to 3.10 until we are ready to commit to 4.0.0 in the apps
> fix(deps): revert dev dependency on editor back to 3.10.0

- CHANGELOG.md
- addon/components/document-title-plugin/insert-title-card.hbs
- addon/components/document-title-plugin/insert-title-card.ts
- addon/plugins/article-structure-plugin/commands/insert-structure.ts
- addon/plugins/document-title-plugin/commands/insert-document-title.ts
- addon/plugins/document-title-plugin/nodes/document-title.ts
- addon/plugins/document-title-plugin/nodes/index.ts
- addon/utils/_private/find-insertion-range.ts
- app/components/document-title-plugin/insert-title-card.js
- app/styles/document-title-plugin.scss
- tests/dummy/app/controllers/regulatory-statement-sample.ts
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/regulatory-statement-sample.hbs
- translations/en-US.yaml
- translations/nl-BE.yaml
This PR adds a document-title plugin containing the document-title widget and node-spec contained in the regulatory-statements frontend so it can be
https://binnenland.atlassian.net/browse/GN-4416?atlOrigin=eyJpIjoiMTcwOTZhMWFmN2JlNDYwZDkyNmIwNDMzN2ZjYjc4YjAiLCJwIjoiaiJ9
- Visit the regulatory-statements dummy route
- Insert a document-title
- Note: in the future, we can still move this functionality into the `article-structure-plugin`.
> Addition of a document-title plugin

- CHANGELOG.md
- addon/components/variable-number/number.ts
The number variable node used the import statement `import { service } from '@ember/service'` which is not supported in ember 3.28. This PR changes the statement to `import { inject as service } from '@ember/service'`
> Fix ember 3.28 compatibility of number variable node

- CHANGELOG.md
- app/styles/variable-plugin.scss
Before the tooltip box would look like this:
With too much padding between the input and other buttons.
Now it looks like this:
I added some 5px padding too, as before everything sticked together a bit too much.
No ticket was created, as I saw this when testing a different PR.
Add a number variable and you'll see the difference.
> Fix number variable tooltip's css when inside a header

- CHANGELOG.md
- package-lock.json
- package.json
`ember-auto-import` 2.6.x gives issues in combination with `ember-resources`, so this PR reverts and pins `ember-auto-import` to 2.5.x
> Revert ember-auto-import to 2.5.0 and pin ember-auto-import to 2.5.x

- CHANGELOG.md
- package-lock.json
- package.json
- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
bumps ember-rdfa-editor to the next "major" release. Includes some nice fixes for ember-nodes, so handy for the current tickets that are being worked on.
Check the release notes: https://github.com/lblod/ember-rdfa-editor/releases/tag/v4.0.0
Two most important aspects:
- stopEvent and ignoreMutation work differently for ember-nodes. This *should* just work better and not break anything. But to "test" this, you should see if plugins using ember-nodes still work as expected. (think of key-bindings and the likes)
- doc nodespec needs a `toDom` function. This is done by using `docWithConfig`. Without this, error will happen.
I haven't done bumping of dependency before, so don't make the assumption this is the correct way to do it. Please actually review :)
> update ember-rdfa-editor from 3.10 to 4.0

- CHANGELOG.md
- addon/components/snippet-plugin/snippet-insert.ts
All snippets are essentially full documents, we cannot just insert one `doc` into another `doc`. Did not see that when just trying to insert "bold" text, but started failing on bigger structures.
> GN-4323: Snippet insertion fix

- .gitignore
- CHANGELOG.md
- README.md
- addon/components/template-comments-plugin/edit-card.hbs
- addon/components/template-comments-plugin/edit-card.ts
- addon/components/template-comments-plugin/insert.hbs
- addon/components/template-comments-plugin/insert.ts
- addon/components/template-comments-plugin/template-comment.hbs
- addon/components/template-comments-plugin/template-comment.ts
- addon/plugins/template-comments-plugin/index.ts
- addon/plugins/template-comments-plugin/node.ts
- app/components/template-comments-plugin/comment-editor.js
- app/components/template-comments-plugin/edit-card.js
- app/components/template-comments-plugin/insert-template-comment.js
- app/components/template-comments-plugin/insert.js
- app/components/template-comments-plugin/template-comment.js
- app/styles/template-comments-plugin.scss
- package-lock.json
- package.json
- tests/dummy/app/controllers/regulatory-statement-sample.ts
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/regulatory-statement-sample.hbs
- translations/en-US.yaml
- translations/nl-BE.yaml
This adds "template comments": a block of text that can be inserted "anywhere" to give some extra explanation how to fill in a document.
This text is only informational and should be hidden at publishing (_currently not implemented yet_).
Also bumps editor to [4.2.0](https://github.com/lblod/ember-rdfa-editor/releases/tag/v4.2.0). This does not include any breaking changes, but does include changes needed for this PR.
- [template comments GN-4264](https://binnenland.atlassian.net/browse/GN-4264)
- [ember-rdfa-editor#908 PR for embedded-editor changes](https://github.com/lblod/ember-rdfa-editor/pull/908)
Need https://github.com/lblod/ember-rdfa-editor/pull/908
- use `npm link` in `ember-rdfa-editor`
- use `npm link @lblod/ember-rdfa-editor` in this repo
- run `ember ts:precompile' in …
> add `template comments` support

- CHANGELOG.md
- addon/components/citation-plugin/helpers/alert-load-error.hbs
- addon/components/snippet-plugin/helpers/alert-load-error.hbs
The wrong contact email address (`gelinkt-notuleren@vlaanderen.be`) was used in some error components. This PR updates that email address to the correct one: `gelinktnotuleren@vlaanderen.be`.
Jira: https://binnenland.atlassian.net/browse/GN-4446?atlOrigin=eyJpIjoiNTlmNzg1OTBjZjNmNDczZmJiOTFkYmUwOWM0M2IyZjQiLCJwIjoiaiJ9
> GN-4446: fix email-address formatting in error components (hotfix)

- CHANGELOG.md
- addon/plugins/article-structure-plugin/structures/article-paragraph.ts
Allows to insert `inline*` content in `article_paragraph`, that helps insert `table` among other stuff.
https://binnenland.atlassian.net/browse/GN-4370
1. Checkout
Observe that it is not possible to reproduce issue with inserting table in article paragraph described in https://binnenland.atlassian.net/browse/GN-4370, this does not stop from inserting table into other article nodes, the fix is implemented in `embed-rdfa-editor` MR https://github.com/lblod/ember-rdfa-editor/pull/911
> GN-4370: Allow block content in `article_paragraph`

- CHANGELOG.md
- addon/components/roadsign-regulation-plugin/expanded-measure.hbs
- addon/components/roadsign-regulation-plugin/expanded-measure.ts
- addon/components/roadsign-regulation-plugin/measure-template.ts
- addon/components/roadsign-regulation-plugin/roadsigns-table.hbs
-------
The endpoint configuration wasn't properly passed through to the code that fetched the individual
instructions in the measure template, to render out the final version.
As a result the roadsign measure list no longer showed the rendered templates before inserting.
This has actually been broken since may, I'm not quite sure how we (and the testers) missed this
for this long.
[GN-4451](https://binnenland.atlassian.net/browse/GN-4451)
I think it should be pretty obvious no matter how you run the plugin
> GN-4451: fix roadsign plugin no longer showing rendered templates in modal

- CHANGELOG.md
- README.md
- addon/components/template-comments-plugin/template-comment.hbs
- addon/components/template-comments-plugin/template-comment.ts
- addon/plugins/template-comments-plugin/index.ts
- addon/plugins/template-comments-plugin/node.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
- tests/dummy/app/templates/regulatory-statement-sample.hbs
Template comments had some problems by trying to avoid allowing `<em>` marks inside its content. The problem was that lists also needed to be allowed, but lists (and their button functionality) would use normal paragraphs again. 
This PR allows normal paragraphs for template nodes, removing the constraint of avoiding `<em>` marks. It also includes some cleanup cherry-picked from another PR.
- cherrypicked cleanup commits from https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/236
- A discussino of the problems with the custom paragraphs and list can be found in the comments of https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/241
- because this simplifies template comments, no specific ember-rdfa-editor version is needed 
-  related bug with lists in template …
> Simplify template comments to fix bugs: allow any content and any marks of the doc schema

- CHANGELOG.md
- addon/plugins/variable-plugin/utils/address-helpers.ts
- addon/plugins/variable-plugin/variables/address.ts
- addon/utils/constants.ts
This PR adds WGS84 (https://en.wikipedia.org/wiki/World_Geodetic_System) coordinates to address variables. The coordinates are fetched alongside the addresses from the location register (https://geo.api.vlaanderen.be/geolocation/v4/Location). 
The geo namespace is used (https://www.w3.org/2003/01/geo/) in order to represent the coordinates.
Jira: https://binnenland.atlassian.net/browse/GN-4262?atlOrigin=eyJpIjoiMWIxMDJiZmFhOWViNGQ1M2ExN2UzODM1N2NlMTU5MzkiLCJwIjoiaiJ9
- Insert and fill in an address
- Check if the coordinates are stored in the address node attributes
- Check if the coordinates are correctly serialized to HTML
- Check if the coordinates are correctly parsed from HTML
- Check if the coordinates correspond to the selected address
Aside from WGS84 coordinates, the location …
> GN-4262: addition of WGS84 coordinates to address variables

- CHANGELOG.md
- README.md
- addon/components/loading-alert.hbs
- addon/components/loading-alert.ts
- addon/components/variable-plugin/address/edit.hbs
- addon/components/variable-plugin/address/edit.ts
- addon/components/variable-plugin/address/nodeview.ts
- addon/plugins/variable-plugin/utils/address-helpers.ts
- addon/plugins/variable-plugin/variables/address.ts
- addon/utils/constants.ts
- app/components/loading-alert.js
- tests/dummy/app/templates/besluit-sample.hbs
- tests/dummy/app/templates/regulatory-statement-sample.hbs
- translations/en-US.yaml
- translations/nl-BE.yaml
This PR attempts to improve the UX and UI when editing an address variable.
It includes the following:
- The UI of the address-edit card has been updated to provide seperate fields for the municipality, streetname, housenumber and busnumber.
- The municipality can be prefilled with a default value
- Both the municipality and streetname fields are implemented using `ember-powerselect` and provide auto-completion
- Both the housenumber and busnumber are simple input fields, each time these are updated, the address is resolved using the address register (https://docs.basisregisters.vlaanderen.be/) (with a delay), to validate if the address exists.
1. First, the user can select a municipality using the muncipality dropdown menu. This field can already be prefilled if desired. The autocomplete …
> GN-4263: update address variable according to updated design

- CHANGELOG.md
- addon/components/variable-plugin/number/insert.hbs
- addon/components/variable-plugin/number/insert.ts
This PR adds functionality which checks the validity of the min/max input fields each time their value changes. It uses the `checkValidity` API for this.
https://binnenland.atlassian.net/browse/GN-4436?atlOrigin=eyJpIjoiOTEyNTdlNWI4OWU5NDIxNjgyZDAzMWMzY2ZkYzBlZTkiLCJwIjoiaiJ9
- Open the number insert card on firefox
- Input text which is not a number in the minimum/maximum fields
- An error message should show up and the `insert` button should be disabled.
> Number variable: check validity of min/max input fields

- CHANGELOG.md
- addon/plugins/snippet-plugin/utils/fetch-data.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
- tests/dummy/app/templates/regulatory-statement-sample.hbs
Add ORDER to snippet list query
Leftover from https://binnenland.atlassian.net/browse/GN-4322
1. Checkout
2. `ember serve`
Observe that snippet lists shown in `Manage snippet lists` modal are ordered by `createdOn`
> GN-4322: Add ORDER to snippet list query

- CHANGELOG.md
- addon/components/variable-plugin/codelist/edit.ts
- addon/components/variable-plugin/codelist/insert.hbs
- addon/components/variable-plugin/codelist/insert.ts
- addon/plugins/variable-plugin/utils/attribute-parsers.ts
- addon/plugins/variable-plugin/variables/codelist.ts
- translations/en-US.yaml
- translations/nl-BE.yaml
Adds a single/multi select config when inserting codelist variables.
Also makes the codelist node save the configuration, and the edit component respect the config
if it exists. If it doesn't, it reverts back to the "selectionStyle" of the codelist as defined
on the remote.
As far as I can tell this is fully backwards compatible.
just run
> GN-4330: allow per-instance config of single/multi-select styles

- CHANGELOG.md
- package-lock.json
- package.json
ember-modifier was aleady used before in number-variable. This adds this dependency to peerDependencies, to make it more explicit that this package is required. 
I tested if stuff still worked, but not sure if this is correct :shrug: 
Note that I took the version used by other packages, as this is likely the version that was used during coding. There does exists a newer version of ember-modifier.
> Add ember-modifier as peerDependency

- .woodpecker/.changelog.yml
- .woodpecker/.test.yml
- CHANGELOG.md
This PR moves the changelog check to a seperate CI pipeline. This ensures that the main CI pipeline still runs even if a changelog change is missing, as some PRs do not require a changelog change.
> Move changelog check to seperate CI pipeline

- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
This PR enables the following plugins in the dummy applications:
- firefoxCursorFix
- chromeHacksPlugin
- lastKeyPressedPlugin
- linkPasteHandler
> Enable additional prosemirror plugins in dummy apps

- CHANGELOG.md
- addon/components/variable-plugin/number/nodeview.hbs
- addon/components/variable-plugin/number/nodeview.ts
See https://github.com/lblod/ember-rdfa-editor/pull/962
this refactors the code to use some new modifiers defined in the editor repo.
https://github.com/lblod/ember-rdfa-editor/pull/962
`npm link` the editor repo and `npm link @lblod/ember-rdfa-editor` this repo. the `ember serve` this repo.
add a number variable
make sure nothing of functionality changed for arrow keys (left/right) and pressing enter. Arrow keys should let you go out of the number variable, enter should set the cursor behind the number variable node.
-
> Use modifiers in number-variable

- .changeset/violet-hats-sneeze.md
- README.md
- addon/components/variable-plugin/address/insert-variable.hbs
- addon/components/variable-plugin/address/insert-variable.ts
- addon/components/variable-plugin/address/insert.ts
- addon/components/variable-plugin/address/utils.ts
- app/components/variable-plugin/address/insert-variable.js
- tests/dummy/app/controllers/regulatory-statement-sample.ts
Address variable had an insert component for inserting it via the general "insert menu". However, this did not allow adding a label and the button is different from that of other variables.
This adds a specific insert-variable component meant to be used in the variable dropdown component.
- has the same button as other variable inserts
- also allows inputting a label
found while updating embeddable. Not connected ticket.
The address variable is added to the list of variables in the dropdown.
Add it, see that the button is the same as the others, see that setting a label works.
also look at the other insert button (under the insert menu): see that this still works.
I don't think the default label is translated at this point. This is probably what is getting fixed in #297 
As usual, …
> Address Variable: add specific variable insert component that includes label logic

- .changeset/sharp-cobras-act.md
- README.md
- index.js
- package-lock.json
- package.json
ember source and data are peerdeps, so we should add them as such. As a bonus, bumps ember and ED
for the dev setup to 4.12 cause why not.
EDIT about 4 hours later:
this turned into quite the rabbithole. Essentially I wanted to test the new setup in GN, since I
wasn't convinced the standard template plugin was being hit in the dummy app
So naturally I `npm link`ed the plugins there.
To my surprise I got a runtime error from ember-resources. It seemed to think that it now lived in
a 4.12 app, even though GN is 4.8. So after some digging I figured this could be due to
the awkwardness of `npm link`.
I found [yalc](https://www.npmjs.com/package/yalc) which seemed promising. It _actually_ publishes
your package to a "local registry" and then allows to "really" install in in your host.
This ran …
> bump ember deps and add them to peerDeps

- .changeset/brave-pigs-sing.md
- README.md
- addon/components/citation-plugin/citations/search-modal.hbs
- addon/components/citation-plugin/citations/search-modal.ts
- addon/plugins/citation-plugin/index.ts
- addon/plugins/citation-plugin/utils/legal-documents.ts
- addon/plugins/citation-plugin/utils/public-decisions.ts
- tests/dummy/app/controllers/besluit-sample.ts
- translations/en-US.yaml
- translations/nl-BE.yaml
Builds on top of https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/275 to add filter by government name. 
https://binnenland.atlassian.net/browse/GN-4266
1. Checkout
See the video
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/assets/769698/5e896602-71aa-441f-80ce-09f60475569e
Instead of providing a dropdown to select a government I decided it's better to allow user to enter the name, this absolves out from figuring out how to fetch the correct names. It also allows user to provide the default filter easier, as there is no need to map from a government ID to a government name.
> GN-4266: Filter by government name

- .changeset/brown-doors-tease.md
- README.md
RDFa date and TOC plugin both didn't really have an explanation of their config.
This was needed for Embeddable, so I added the explanation to this repo too.
I checked via PR, code and also Elena if the TOC explanation is correct. So only the wording should be up for debate :)
> Add missing config explanation for TOC and rdfa date

- .changeset/seven-trainers-wink.md
- .changeset/shaggy-kiwis-talk.md
- addon/plugins/rdfa-date-plugin/nodes/date.ts
- addon/plugins/table-of-contents-plugin/nodes/table-of-contents.ts
- addon/plugins/template-comments-plugin/node.ts
- addon/plugins/variable-plugin/variables/address.ts
- addon/plugins/variable-plugin/variables/codelist.ts
- addon/plugins/variable-plugin/variables/location.ts
- addon/plugins/variable-plugin/variables/number.ts
- addon/plugins/variable-plugin/variables/text.ts
- package-lock.json
- package.json
This PR updates the `@lblod/ember-rdfa-editor` package to version 6.0.0. Version 6.0.0 of the editor is a breaking release which includes changes to the ember-node API (the `component` helper is no longer used). 
Specifically, this PR includes the following changes:
- Update to `@lblod/ember-rdfa-editor` 6.0.0
- Increase the ``@lblod/ember-rdfa-editor` peer-dependency semver range to `^6.0.0`
- Addition of the `@glint/template` package
- Addition of `@glint/template` to this project peer-dependencies (see https://typed-ember.gitbook.io/glint/troubleshooting/migrating#glint-template-peer)
- Update the ember-nodes of this project to respect the new API
- npm start
- ensure that all ember-nodes work as before
> Update `@lblod/ember-rdfa-editor` to version 6.0.0

- .changeset/tricky-needles-shake.md
- addon/components/decision-plugin/decision-plugin-card.hbs
- addon/components/snippet-plugin/snippet-list/snippet-list-view.hbs
- addon/components/template-comments-plugin/template-comment.hbs
- addon/components/variable-plugin/number/insert.hbs
- app/styles/besluit-plugin.scss
- app/styles/date-plugin.scss
- app/styles/snippet-plugin.scss
- app/styles/template-comments-plugin.scss
- app/styles/variable-plugin.scss
* Mostly add `say-` prefix for CSS classes that sound like they are too generic.
* Remove unused `span.date` class
https://binnenland.atlassian.net/browse/GN-4517
1. Checkout
Make sure classes are still applying where they should be
> GN-4517: Reduce possible CSS conflicts

- .changeset/new-ears-clap.md
- addon/components/citation-plugin/citation-card.ts
If the `defaultDecisionsGovernmentName` is present provide it in `filter` to `fetchLegalDocuments`
Inline search for citation plugin insert card did not pass provided `defaultDecisionsGovernmentName` to the query. It does now.
https://binnenland.atlassian.net/browse/GN-4534
1. Checkout
1. Go to "Besluit Sample", try typing `besluit jaar` (inside motivering)
1. Observe that documents appearing in the citation insert card in the sidepanel are for Edegem only
> GN-4534: Citation insert card filter enhancement

- .changeset/nine-otters-behave.md
- addon/components/variable-plugin/address/edit.hbs
This PR ensures that users are able to clear the municipality and street inputs when editing an address variable. This is implemented by passing the `allowClear` argument to the `power-select` components.
[GN-4502](https://binnenland.atlassian.net/browse/GN-4502?atlOrigin=eyJpIjoiMzRhYzI1NjI3Nzc3NDQ3M2I3ZDkyMjVkZTcyZDIwYjIiLCJwIjoiaiJ9)
- Insert an address variable and select it
- Notice that when the street/municipality fields are filled out, you can clear their value
- When clearing the street input, the housenumber and busnumber fields should also be cleared
- When clearing the municipality input, all other fields should also be cleared
> GN-4502: allow municipality and street field of address plugin to be cleared

- .changeset/clean-rats-wash.md
- addon/components/variable-plugin/address/edit.ts
- addon/plugins/variable-plugin/utils/address-helpers.ts
- translations/en-US.yaml
- translations/nl-BE.yaml
Instead of telling the user that there is no address, offer the user to use just the street for the address.
https://binnenland.atlassian.net/browse/GN-4501
1. Checkout
Have a look at the video
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/assets/769698/e15f890f-bb94-413e-a094-d300e9d02384
I've chosen to use more general language when offering user to just use the street, ticket asks for 
> This housenumber doesn’t exist in the selected street, provide another housenumber or proceed without adding a housenumber
But this text will not work, if the house number was correct but the user is now trying to enter bus number. So I went with a more generic notice.
> GN-4501: Fail gracefully when house number does not exist

- .changeset/tough-planes-smell.md
- README.md
- addon/components/variable-plugin/date/edit.hbs
- addon/components/variable-plugin/date/edit.ts
- addon/plugins/variable-plugin/variables/date.ts
The config and readme already included the option `allowCustomFormat`, but this did not do anything. This PR fixes so that if `allowCustomFormat` is set to `false`, a custom format can't be used.
https://binnenland.atlassian.net/browse/GN-4524
Change the config (depending on your test). 
If `allowCustomFormat` is set to false, the radio button `custom format` should be disabled.
If the config option is missing (or set to true), the radio button should work.
In all older documents the date variable should always allow custom format (e.g. export and import some html of an older editor version, like the dev version) 
- The default for this is set to true by default everywhere. This follows how it was before: regardless of the config option, custom formats were allowed. This makes this a …
> GN-4524: date variable - fix config option to disable custom format 

- .changeset/thin-shoes-train.md
- addon/plugins/variable-plugin/utils/address-helpers.ts
GN-4538: Show empty search result when there are no streets
Issue was caused by `straatnaam` field not existing in the response when there are no streets found.
https://binnenland.atlassian.net/browse/GN-4538
1. Checkout
1. Insert address
2. Try to search for an existing street e.g. Drongenstationstraat in Gent
3. Select the result
4. Now search for non-existing street
5. Observe that you see "no streets found" notification instead of the results of previous search
> GN-4538: Show empty search result when there are no streets

- .changeset/afraid-falcons-walk.md
- addon/plugins/standard-template-plugin/index.ts
- addon/plugins/standard-template-plugin/utils/instantiate-uuids.ts
- addon/utils/memoize.ts
Export `instantiateUuids` for downstream use, improve typing of `memoize` util as well as how it handles non-existent arguments.
https://binnenland.atlassian.net/browse/GN-4505
https://github.com/lblod/frontend-gelinkt-notuleren/pull/586
https://github.com/lblod/frontend-reglementaire-bijlage/pull/192
Needs PR version of GN to test, otherwise the library function is not used
Instantiate a regulatory statement and inspect to verify uuids.
It was unclear whether having separate `generateUuids` and `generateBoundUuids` functions was preferable to having just one function with an optional argument. Switching to just one overloaded function is trivial, but it's unclear if the current `generateBoundUuids` is used elsewhere already or not.
> GN-4505 Export instantiateUuids and improve memoization function

- .changeset/khaki-schools-clap.md
- .changeset/smart-fireants-sniff.md
- .changeset/swift-penguins-roll.md
- README.md
- addon/components/document-title-plugin/insert-title-card.ts
- addon/components/variable-plugin/number/nodeview.ts
- addon/plugins/article-structure-plugin/commands/insert-structure.ts
- addon/plugins/article-structure-plugin/commands/move-selected-structure.ts
- addon/plugins/article-structure-plugin/commands/wrap-structure-content.ts
- addon/plugins/article-structure-plugin/index.ts
- addon/plugins/article-structure-plugin/structures/article-paragraph.ts
- addon/plugins/article-structure-plugin/structures/article.ts
- addon/plugins/article-structure-plugin/structures/chapter.ts
- addon/plugins/article-structure-plugin/structures/section.ts
- addon/plugins/article-structure-plugin/structures/subsection.ts
- addon/plugins/article-structure-plugin/structures/title.ts
- addon/plugins/decision-plugin/commands/insert-motivation.ts
- addon/plugins/standard-template-plugin/utils/nodes.ts
- addon/plugins/variable-plugin/utils/number-to-words.ts
- addon/plugins/variable-plugin/variables/number.ts
- addon/utils/translation.ts
- package-lock.json
- package.json
There was a ticket for already partially using document language for plugins: https://binnenland.atlassian.net/browse/GN-4450
This fixes all other instances where translations still had to happen.
The clue is that anything that shows up in the document (part of the "reading" experience") should be in the language of the document.
Number variable: interestingly, a very recent n2words added support for a general language as locale. So no special logic needed for that
Placeholders: placeholders are part of the document and are translated with doc language.
https://binnenland.atlassian.net/browse/GN-4424
- Check if number as words translates based on the doc language
- Check if placeholders follow this language (e.g. article structures, decision structures).
- This PR is a bit rushed, so I …
> Make plugins follow document language where applicable (show as words & placeholders)

- .changeset/clever-pets-press.md
- README.md
- addon/components/variable-plugin/insert-variable-card.hbs
- addon/components/variable-plugin/insert-variable-card.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
This PR drops all usages of the dynamic `component` helper in this package in preparation for embroider-compatibility.
This removal also causes a change in the variable-plugin insert-component API, the insert-components now need to be passed directly (instead of their path). 
Before:
```typescript
get variableTypes(): VariableConfig[] {
return [
{
label: 'text',
component: {
path: 'variable-plugin/text/insert',
},
},
{
label: 'location',
component: {
path: 'variable-plugin/location/insert',
options: {
endpoint: 'https://dev.roadsigns.lblod.info/sparql',
},
},
},
];
}
```
After:
```typescript
import TextVariableInsertComponent from '@lblod/ember-rdfa-editor-lblod-plugins/components/variable-plugin/text/insert';
import LocationInsertComponent from …
```
> Drop usage of component-helper

- .changeset/eleven-grapes-greet.md
- app/styles/citaten-plugin.scss
GN-4130: Move styles for `data-editor-highlight` 
Styles that were applied to elements with the `data-editor-highlight` attribute (used by `citation-plugin`) moved from [editor repository](https://github.com/lblod/ember-rdfa-editor/pull/1013) to [ember-rdfa-editor-lblod-plugins](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/343) as part of the `citation-plugin`.
https://binnenland.atlassian.net/browse/GN-4130
1. Checkout https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/343
2. Checkout https://github.com/lblod/ember-rdfa-editor/pull/1013
3. Build `ember-rdfa-editor`
4. `yalc publish` the `ember-rdfa-editor`
5. `yalc add @lblod/ember-rdfa-editor` inside `ember-rdfa-editor-lblod-plugins`
Confirm that styling is still shown correctly for inline citation search, …
> GN-4130: Add styles for `data-editor-highlight`

- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
This PR disables the `space` invisible in the dummy application as it causes large slowdowns when pasting large documents/typing in large documents.
The other formatting marks (pilcrow and carriage return) do not cause a large slowdown as they are way more sparse.
[GN-4617](https://binnenland.atlassian.net/browse/GN-4617?atlOrigin=eyJpIjoiODUxN2E2NWYzZWQ0NGMxMDk0NzNlNmUxNDEwY2I4ZTUiLCJwIjoiaiJ9)
https://github.com/lblod/ember-rdfa-editor/pull/1057
See https://github.com/lblod/ember-rdfa-editor/pull/1057
Note: this PR does not contain any changesets as it only contains internal changes.
> GN-4617: disable space-invisible in dummy app

- addon/plugins/article-structure-plugin/commands/insert-structure.ts
- addon/plugins/article-structure-plugin/commands/move-selected-structure.ts
- addon/plugins/article-structure-plugin/commands/recalculate-structure-numbers.ts
- addon/plugins/article-structure-plugin/commands/remove-structure.ts
- addon/plugins/article-structure-plugin/commands/unwrap-structure.ts
- addon/plugins/article-structure-plugin/commands/wrap-structure-content.ts
- addon/plugins/article-structure-plugin/index.ts
- addon/plugins/article-structure-plugin/structures/article-paragraph.ts
- addon/plugins/article-structure-plugin/structures/article.ts
- addon/plugins/article-structure-plugin/structures/chapter.ts
- addon/plugins/article-structure-plugin/structures/index.ts
- addon/plugins/article-structure-plugin/structures/section.ts
- addon/plugins/article-structure-plugin/structures/structure-header-number.ts
- addon/plugins/article-structure-plugin/structures/structure-header-title.ts
- addon/plugins/article-structure-plugin/structures/structure-header.ts
- addon/plugins/article-structure-plugin/structures/subsection.ts
- addon/plugins/article-structure-plugin/structures/title.ts
- addon/plugins/article-structure-plugin/utils/structure.ts
- addon/plugins/standard-template-plugin/utils/nodes.ts
- addon/utils/_private/find-insertion-range.ts
- addon/utils/namespace.ts
- app/styles/article-structure-plugin.scss
- tests/dummy/app/controllers/editable-node.ts
- tests/dummy/app/templates/editable-node.hbs
Correctly support the insertion of any structures in the article structures plugin.
All comments should have been addressed, with the exception of pressing enter in the titles, which still creates a whole new structure with a new title. There are some design issues, but since we'll need to overhaul the design for editable nodes, I haven't done any tweaking.
This is made towards #357 with the intent that it collects all of the related changes rather than them being merged straight to master.
[PR on editor repo](https://github.com/lblod/ember-rdfa-editor/pull/1062)
The 'editable nodes' route should now have the article structure plugin enabled.
Inserting structure elements should function as expected.
> Update article structure plugin to support rdfa editing

- .changeset/khaki-ads-travel.md
- addon/plugins/confidentiality-plugin/marks/redacted.ts
- app/styles/confidentiality-plugin.scss
Switch out styling of redacted text with that supplied by a designer for the PoC.
PR for embeddable: https://github.com/lblod/frontend-embeddable-notule-editor/pull/188
N/A
Redact some text and see the inline icon. Select, etc. should still work and not be influenced by the icon.
Uncertain if there is a weird selection behaviour that is broken by adding a psuedo element which takes up space.
> Use designer supplied styling for redacted text

- .changeset/strange-rockets-deliver.md
- package-lock.json
- package.json
This PR includes an increase of the peerdependency requirement of `@appuniversum/ember-appuniversum` package to `^2.15.0`.
The main reason for this stricter requirement is to be able to use features of the more recent versions of the package.
Additionally, this PR also pins the `@appuniversum/ember-appuniversum` to the lowest supported version (2.15.0).
> Increase `@appuniversum/ember-appuniversum` peerdependency requirement to `^2.15.0`

- .changeset/little-news-protect.md
- package-lock.json
- package.json
This PR drops support for ember 4.8.
The supported `ember-source` version range is now `^4.12.0`
Ember 5.x is not yet officially supported.
Additionally, this PR also pins the `ember-source` devdep to the lowest supported version (4.12.0).
> Drop support for ember 4.8

- package-lock.json
- package.json
This PR pins the remaining devdependencies which are included as peerdependencies to the lowest supported version.
- `ember-modifier` to 3.2.7
- `@glint/template` to 1.1.0
- `ember-power-select` to 6.0.0
This PR is part of a change of strategy to test this addon with the lowest supported peerdependency versions. This way, we can't accidentally include features of these packages which are not supported by their whole peerdependency range.
> Pin devdependencies which are included as peerdependencies to the lowest supported version

- addon/plugins/article-structure-plugin/structures/article-paragraph.ts
- addon/plugins/article-structure-plugin/structures/structure-header-number.ts
- addon/plugins/article-structure-plugin/structures/structure-header-title.ts
- addon/plugins/article-structure-plugin/structures/structure-header.ts
- addon/plugins/article-structure-plugin/utils/structure.ts
- tests/dummy/app/controllers/editable-node.ts
Use the (now exported) `getRdfaContentElement` helper to target the content-container element in article structure nodes in a way that supports importing the content directly if this element does not exist. This allows to correctly import pre-rdfa-aware html documents.
Depends on https://github.com/lblod/ember-rdfa-editor/pull/1077
Need to link the [feat/content-predicate](https://github.com/lblod/ember-rdfa-editor/tree/feat/content-predicate) branch of the editor.
Get an export from an old version of the article structure plugin, for example from staging. Set the variable `presetContent` in `tests/dummy/app/controllers/besluit-sample.ts#334` to be equal to this html. Alternatively you can add it to the sample-data.ts of your locally linked editor repo.
There are some issues with the …
> Backwards compatability of article structure nodes

- .changeset/afraid-tips-visit.md
- .changeset/chilly-ravens-think.md
- addon/plugins/template-comments-plugin/node.ts
- app/styles/citaten-plugin.scss
- app/styles/confidentiality-plugin.scss
- app/styles/template-comments-plugin.scss
This PR contains the following changes/improvements:
- Usage of the same title for template comments in the dynamic and static versions
- Removal of `@import "ember-appuniversum"` statements on top of the different sass modules, in order to prevent style overriding.
- Addition of the `say-template-comment` class to the static version of template comments.
- Addition of some extra styles to the `say-template-comment` class.
- Solves [GN-4654](https://binnenland.atlassian.net/browse/GN-4654?atlOrigin=eyJpIjoiZGQ5MDdlY2NlMzZkNDZlZjkyYzcyOGI4NDc1NzU2MDEiLCJwIjoiaiJ9) partially
- https://github.com/lblod/frontend-reglementaire-bijlage/pull/220
- `npm link`
- `npm link @lblod/ember-rdfa-editor-lblod-plugins` on master of `frontend-reglementaire-bijlagen`
- Start the …
> GN-4654: improved template-comment styling

- addon/components/variable-plugin/address/utils.ts
- addon/components/variable-plugin/codelist/insert.ts
- addon/components/variable-plugin/date/edit.ts
- addon/components/variable-plugin/date/insert-variable.ts
- addon/components/variable-plugin/date/insert.ts
- addon/components/variable-plugin/number/insert.ts
- addon/components/variable-plugin/number/nodeview.hbs
- addon/components/variable-plugin/number/nodeview.ts
- addon/components/variable-plugin/text/insert.ts
- addon/plugins/variable-plugin/variables/address.ts
- addon/plugins/variable-plugin/variables/codelist.ts
- addon/plugins/variable-plugin/variables/date.ts
- addon/plugins/variable-plugin/variables/number.ts
- addon/plugins/variable-plugin/variables/text.ts
- addon/utils/namespace.ts
This should fix at least variables.
Requires https://github.com/lblod/ember-rdfa-editor/pull/1021
N/A
Inserting variables (except location), reloading and parsing old editor output should maintain the variable structures.
N/A
> Cleanup issues from hasty conversion of nodes to datatype branch

- .changeset/sour-zebras-carry.md
- addon/components/template-comments-plugin/template-comment.ts
- addon/plugins/template-comments-plugin/node.ts
- translations/en-US.yaml
- translations/nl-BE.yaml
This PR simplifies the label/header/name of template-comments in the following manner:
- In dutch: from 'toelichtings- en voorbeeldbepaling' to 'toelichting'
- In english: from 'template comment or example' to 'template comment'
[GN-4722](https://binnenland.atlassian.net/browse/GN-4722?atlOrigin=eyJpIjoiNjkyMTY1N2YyZWExNDlmZmJjMzk1MDQyYjVjNGE3YzkiLCJwIjoiaiJ9)
- Open the 'regulatory statements' dummy app
- Insert a template-comment
- Notice that the insertion buttons/navigational buttons/heading have changed
- The html output should also have the desired changes
> GN-4722: simplify label of template-comments

- addon/plugins/article-structure-plugin/structures/article-paragraph.ts
- addon/plugins/article-structure-plugin/structures/structure-header-number.ts
- addon/plugins/article-structure-plugin/utils/structure.ts
- tests/dummy/app/controllers/editable-nodes-regulatory-statement.ts
Some more parsing problems for article structure nodes (I could have sworn I fixed these already :s ).
I also changed the configuration of the editor in the editable-nodes-regulatory-statement test page to be almost the same as that on the RS frontend project.
https://github.com/lblod/ember-rdfa-editor/pull/1139
N/A
Construct a RS document on QA, export, then import into the RS editable node sample page and confirm the nodes are all recreated correctly.
It seems there are some problems with parsing, as noted in chat.
> More article structure parsing and aligning sample with RS frontend

- .changeset/wet-baboons-serve.md
- addon/commands/index.ts
- addon/commands/replace-selection-and-select-node.ts
- addon/components/variable-plugin/codelist/insert.ts
- addon/components/variable-plugin/date/insert-variable.ts
- addon/components/variable-plugin/date/insert.ts
- addon/components/variable-plugin/location/insert.ts
- addon/components/variable-plugin/number/insert.ts
- addon/components/variable-plugin/text/insert.ts
- addon/plugins/variable-plugin/variables/address.ts
- addon/plugins/variable-plugin/variables/codelist.ts
- addon/plugins/variable-plugin/variables/location.ts
- addon/plugins/variable-plugin/variables/number.ts
- addon/plugins/variable-plugin/variables/text.ts
This PR introduces some changes into what happens after inserting a variable node.
**Before this PR:**
- A text-cursor is set just after the inserted variable (the variable is not focused)
- This causes different issues on both chromium and firefox
* On chromium: no text-cursor is shown
* On firefox: a text-cursor is shown, but does not act as a real selection (typing does not work)
**Modifications introduced in this PR:**
- After variable insertion, the variables is selected/focused, allowing users to directly interact with them
- Similar to how addresses/links behave
- Works on both firefox and chromium
Solves [GN-4732](https://binnenland.atlassian.net/browse/GN-4732?atlOrigin=eyJpIjoiYjdjNzFkYTJjMjg5NDJkZmJlODg4OGY0YzZmMjY2NjUiLCJwIjoiaiJ9)
- `pnpm start`
- Insert a variable (text, …
> GN-4732: ensure variables are selected/focused after insertion

- .changeset/healthy-colts-smoke.md
- .changeset/twenty-peaches-juggle.md
- addon/components/besluit-type-plugin/toolbar-dropdown.hbs
- addon/components/table-of-contents-plugin/toolbar-button.hbs
This PR adds title attributes to:
- The decision-type toolbar button
- The table-of-contents toolbar toggle
[GN-4736](https://binnenland.atlassian.net/browse/GN-4736?atlOrigin=eyJpIjoiNTY3NjJhNTE4ZTViNGYyMGFjMmM4NjliOWRhOWNkMDkiLCJwIjoiaiJ9)
Closes #400
> Addition of missing title attributes

- .changeset/nervous-pillows-dance.md
- package-lock.json
- package.json
Since the changes to `editor` have been made backwards compatible, the plugins can now support either version without changes. This is needed to add the HTML editor to embeddable as the addition of the toolbar button was made on the RDFa aware branch.
https://github.com/lblod/frontend-embeddable-notule-editor/issues/238
N/A
Modify the package.json to set a dev build of the rdfa-aware branch, for example `10.0.0-dev.f918748be0b3f4a01622379b403901024f03eeec` and test that everything works.
N/A
> Update editor peer-dep to include ^10.0.0

- .changeset/wet-oranges-flash.md
- package-lock.json
- package.json
This PR drops support for `@lblod/ember-rdfa-editor` `10.x` range.
Note: this PR is not breaking, the `10.x` range of the `@lblod/ember-rdfa-editor` package never contained stable releases.
We managed to release the new editor version as a `9.x` minor release (and the alpha `10.x` releases are thus obsolete).
N/A
> Drop support for editor `10.x` releases

- .changeset/clean-parrots-beam.md
- addon/plugins/article-structure-plugin/commands/insert-structure.ts
This PR fixes an issue in the `insertStructure` command when passing the `content` argument. It ensures the `wrapStructureContent` command is never attempted when passing the `content` argument.
None
- Insert the sample `DecisionTemplate`
- Insert a roadsign regulation
- Notice that only the article (without any content or roadsign regulation) is inserted.
- Insert the sample `DecisionTemplate`
- Insert a roadsign regulation
- The article with the right roadsign regulation should be inserted.
> article-structures: fix structure insertion with content

- addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
This PR includes some updates to the `roadsign-regulation` plugin to ensure it works correctly in combination with the `rdfa-aware` system.
For now, I've decided to keep using the classic RDFa system for the roadsign regulations.
[GN-4810](https://binnenland.atlassian.net/browse/GN-4810?atlOrigin=eyJpIjoiOTQ5MDNjMDVlN2U4NGNlM2E2MzRmNWZmYzhiNmFlYTIiLCJwIjoiaiJ9)
- Insert a sample decision with decision-type 'Reglementen en verordeningen'
- Ensure that the `Insert traffic measure` inserts a `roadsign_regulation` node correctly in a new article node
- The roadsign regulation should be preserved correctly across reloads
I have decided to hold off moving the `roadsign_regulation` node to the rdfa-aware system as I did not really yet see the point of moving these over.
> GN-4810: get the `roadsign-regulation` plugin working with the `rdfa-aware` decision nodes

- addon/plugins/standard-template-plugin/utils/nodes.ts
This PR removes redundant attributes and parse-rules from the following node-specs:
- `besluit`
- `besluit_title`
- `description`
- `motivering`
- `article_container`
- `besluit_article`
- `besluit_article_content`
The parse-rules of these nodespecs should be able to parse both the old and the new representations.
None
- Import the sample `DecisionTemplate` or copy over a document from GN
- Ensure that all RDFa contained in the decision is correctly parsed and stored.
At the moment, there are still issues in the parsing logic of decision-articles, I will tackle these issues in a seperate PR.
> Removal of redundant attributes and parse-rules from decision node-specs

- .changeset/loud-coins-bathe.md
- addon/components/article-structure-plugin/structure-card.hbs
- addon/components/article-structure-plugin/structure-card.ts
- addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
- addon/plugins/article-structure-plugin/commands/insert-structure.ts
- addon/plugins/article-structure-plugin/commands/recalculate-structure-numbers.ts
- addon/plugins/article-structure-plugin/commands/set-structure-start-number.ts
- addon/plugins/article-structure-plugin/index.ts
- addon/plugins/article-structure-plugin/utils/structure.ts
- addon/plugins/standard-template-plugin/utils/nodes.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
This PR fixes some of the issues related to the rdfa-aware version of decision articles (the `besluit_article` node).
Specifically, this PR includes the following changes:
- The `setStartNumber` and `getStartNumber` properties are now optional. If these are not provided, the feature is not enabled.
- Adjust the `besluit_article` node to work in the `rdfa-aware` system
* The `besluit_article` node is `rdfa-aware`, except for the `eli:number` property
* The `besluit_article_header` node still works using the classic RDFa approach
* The `besluit_article_content` node works using the `rdfa-aware approach
- Adjust `insertStructure` with hacky fix to support decision articles correctly (ensure `ELI('has_part')` predicate is correctly inserted)
- Inserting, moving and removing decision articles …
> Fix behaviour of rdfa-aware decision articles

- .changeset/nervous-paws-yawn.md
- .changeset/sour-peas-hear.md
- .changeset/warm-geese-cheer.md
- .eslintrc.js
- addon/components/loading-alert.hbs
- addon/components/variable-plugin/address/edit.ts
- addon/components/variable-plugin/address/nodeview.ts
- addon/plugins/variable-plugin/utils/address-helpers.ts
- addon/plugins/variable-plugin/variables/address.ts
- addon/utils/constants.ts
Tweak the representation of addresses produced by variable-plugin to conform to the OSLO model.
Includes converting GML location data to WKT as that is used in the spec. The conversion used only works for simple points, but we don't handle anything but this already. Notes as to why I used a regex instead of a full parser are in comments.
https://binnenland.atlassian.net/browse/GN-4838
N/A
Inserting and editing addresses should work correctly. The exported HTML should match the OSLO data model for addresses.
We slightly abuse the model by re-using the id of the address as the resource id, which their examples do not. I assumed this was fine though.
I reverted my changes to use language correctly as it caused too many issues to be worth it, given everything will be in 'nl' (even the name of …
> Use OSLO model for addresses

- tests/dummy/app/controllers/regulatory-statement-sample.ts
- tests/dummy/app/templates/regulatory-statement-sample.hbs
I half moved over on RS-sample, and it caused weird issues. So, move back for now, we'll move both over to the location-plugin and deprecate the variable-plugin version later.
N/A
N/A
Inserting addresses on both sample pages should work, but have different UX.
No changelog as it's only a change on the test app. Is that the right thing to do?
> Move back to address plugin for RS to allow for testing both

- .changeset/kind-forks-smoke.md
- addon/components/snippet-plugin/nodes/placeholder.gts
- addon/components/snippet-plugin/snippet-insert-placeholder.gts
- addon/components/snippet-plugin/snippet-list-select-rdfa.ts
- addon/components/snippet-plugin/snippet-list/snippet-list-modal.ts
- addon/plugins/snippet-plugin/commands/index.ts
- addon/plugins/snippet-plugin/commands/update-snippet-ids.ts
- addon/plugins/snippet-plugin/nodes/snippet-placeholder.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
- translations/en-US.yaml
- translations/nl-BE.yaml
Changed the UI of the snippet placeholder to specify which lists you can insert from.
GN-4852
Insert a snippet placeholder with only a snippet list and check that it shows as described in the ticket, then change it to multiple lists, it should change the UI to show the multiple lists you can insert from 
None
> Added the lists of the snippet placeholder in the prosemirror node

- .changeset/big-pugs-sneeze.md
- addon/components/location-plugin/nodeview.ts
- addon/components/variable-plugin/address/nodeview.ts
- addon/components/variable-plugin/date/nodeview.ts
- addon/components/variable-plugin/location/nodeview.ts
- addon/components/variable-plugin/number/nodeview.ts
- addon/components/variable-plugin/text/insert.ts
- addon/components/variable-plugin/variable/nodeview.ts
- app/styles/variable-plugin.scss
I made so the label is not shown when you fill a variable
GN-4824
You can insert one of each variables and fill it, appreciate that the label is indeed hidden, in some variables you can go back to an unfilled status, and the variable should reappear, but on others this is just not possible because of how the variable UI is made
> Remove label when variable is filled

- .changeset/wet-parrots-end.md
- addon/plugins/variable-plugin/recreateUuidsOnPaste.ts
- package.json
- pnpm-lock.yaml
- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
Copying variable now copies actual variable, not just the text that was inside.
* https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/435
* https://github.com/lblod/ember-rdfa-editor/pull/1195
Should be tested from https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/435
1. Checkout `plugins` PR - https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/435
2. In `plugins` repo `pnpm i` 
3. In `plugins` repo `pnpm run start` 
Variables should be copied verbatim
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/assets/769698/416d5362-1372-419e-9ca6-d64916e55a47
`ember-rdfa-editor` configures `recreateUuidsOnPaste` plugin by default, which _does not_ work with "new" RDFa aware nodes. To avoid breaking change in editor, I've decided to make that particular …
> GN-4820: Copy variables

- .changeset/few-dragons-kick.md
- addon/models/sign.ts
- addon/services/roadsign-registry.ts
When fetching traffic measures from the MOW endpoint, we are also fetching their included traffic signs. These traffic signs may include road signs, traffic lights or road markings. While road signs include a `zonality` property, traffic lights and road markings do not. This PR ensures that the `zonality` property is marked as 'optional' when fetching the traffic signs.
This PR is a more permanent solution for the temporary solution introduced in https://github.com/lblod/frontend-mow-registry/pull/250
- Start the application
- Insert a decision with a decision type which supports insertion of traffic measures
- Ensure insert traffic measures still works. The plugin should now also support inserting traffic measures with traffic signs which do not have a `zonality` property.
> Ensure `zonality` is set up as optional when fetching traffic signs

- .changeset/fair-spoons-tell.md
- addon/components/lmb-plugin/search-modal.ts
- addon/models/mandatee.ts
This PR modifies the `Mandatee` model and mandatee sparql query so that it supports independent mandatees (who are not part of any fraction).
None
This PR requires https://github.com/lblod/app-gelinkt-notuleren/pull/182 to function correctly.
- Start a local instance of the app-gelinkt-notuleren stack
- Start the test-app of this package
- Open up the mandatee-selector modal
- You should be able to view and insert mandatees without a fraction.
> lmb-plugin: ensure independent mandatees (without a fraction) can be selected for insertion

- .changeset/calm-seals-look.md
- addon/components/standard-template-plugin/template-provider.ts
The filtering for templates was wrong: instead of allowing templates that have an empty contexts array anywhere, we were blocking them, this meant that you couldn't insert the 2 main decision templates from the meeting page anymore.
> fix: allow templates with no restrictions everywhere

- .changeset/young-donkeys-develop.md
- .eslintrc.js
- addon/components/confidentiality-plugin/redact.gts
- addon/components/decision-plugin/insert-article.gts
- addon/components/snippet-plugin/nodes/placeholder.gts
- addon/components/snippet-plugin/nodes/snippet.gts
- tests/integration/rdfa/blackbox-test.ts
I spotted some of these in my adventures through the codebase, so thought to change them. I also spotted that my comment about template only components that wasn't necessary (or true), so removed it, and added the eslint config to warn on unused ignores, as well as adding a single demo of a typed template only component.
N/A
N/A
Everything still works!
N/A
> Switch some name based icons to use AU icon components

- .changeset/thick-schools-nail.md
- addon/plugins/snippet-plugin/nodes/snippet.ts
The previous content spec crashed in a schema without the mentioned nodes, like a decision. It turns out you can only mention things in the content spec that exist in your schema.
In any case, we're moving more and more towards looser content specs as that works way better. We should strive to use `block+` in most block-style nodes. 
This does break compatibility with the "old" article-structures, as they are not part of the block group. But since the feature is built for the IV, this is fine.
> fix(snippets): make snippet nodes accept any block as content

- .changeset/seven-days-begin.md
- addon/plugins/lpdc-plugin/api.ts
- tests/dummy/app/controllers/besluit-sample.ts
Allows for convenient use when proxying in an ember app, as the url is relative to the origin and that ensures that cookies are passed correctly for authentication.
Makes configuration of https://github.com/lblod/frontend-gelinkt-notuleren/pull/667 easier.
Should be tested linked to frontend-gn. Tested and working with a local app-gn, dev app-gn gets a 502 response, but that seems unrelated to this change.
Link to frontend-gn on the `GN-4693` branch, set `ENV.lpdcEndpoint` to be `/lpdc-service` and test that 'insert LPDC' in agendapoints works.
N/A
> Add support for relative urls to lpdc service endpoint

- .changeset/early-rivers-chew.md
- addon/commands/insert-data-table.ts
- addon/components/lmb-plugin/search-modal.ts
- addon/components/mandatee-table-plugin/configure.gts
- addon/components/mandatee-table-plugin/insert.gts
- addon/components/mandatee-table-plugin/node.gts
- addon/plugins/besluit-topic-plugin/utils/helpers.ts
- addon/plugins/lmb-plugin/utils/fetchMandatees.ts
- addon/plugins/mandatee-table-plugin/index.ts
- addon/plugins/mandatee-table-plugin/node.ts
- addon/plugins/mandatee-table-plugin/sync-document.ts
- addon/utils/build-data-table.ts
- app/components/mandatee-table-plugin/configure.js
- app/components/mandatee-table-plugin/insert.js
- app/styles/mandatee-table-plugin.scss
- tests/dummy/app/components/synchronize-mandatees.gts
- tests/dummy/app/config/mandatee-table-sample-config.ts
- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/styles/app.scss
- tests/dummy/app/templates/besluit-sample.hbs
- translations/en-US.yaml
- translations/nl-BE.yaml
This PR includes a new mandatee table plugin which includes the following features:
- Addition of a `mandatee_table` node-spec and `mandateeTableView` node-view
* `mandatee_table` nodes support two attributes: `tag` and `title` which can be configured by a template-creator
- Addition of two components used to insert and configure mandatee tables
* `MandateeTablePlugin::Insert` allows a user/template-creator to insert empty `mandatee_table` nodes
* `MandateeTablePlugin::Configure` allows a user/template-creator to configure the title/tag of a `mandatee_table` node
- Addition of a `syncDocument` function.
* Synchronizes the `mandatee_table` nodes in a document based on a supplied configuration
* Can work in a headless way (does not require a prosemirror view). It accepts and outputs a …
> GN-4899: support for dynamic, synchronizable mandatee tables

- .changeset/strange-fishes-lay.md
- addon/components/variable-plugin/codelist/edit.ts
- addon/components/variable-plugin/person/edit.ts
This PR fixes the issue with the unresponsive edit/insert button when a person variable is selected.
Specifically, it replaces the `trackedFunction`  by a simple getter.
**Cause of the issue**
-  The edit/insert card is only shown when selectedPersonNode is not loading and has resolved to a value
- The selectedPersonNode trackedFunction is dependent on the editor state
- When clicking on the edit/insert button outside the editor, a click event is fired => this causes the editor state to change (as the selection is no longer visible)
- The selectedPersonNode trackedFunction is triggered due to a state change and goes into 'loading' mode, which means it no longer has a value (as it is pending) => this causes the card to hide (for only a few ms, but that's enough)
- Due to the card being …
> GN-4949: person-variable-plugin: fix issue with unresponsive edit/insert button

- .changeset/calm-berries-give.md
- addon/components/mandatee-table-plugin/node.gts
- addon/plugins/mandatee-table-plugin/node.ts
- app/styles/mandatee-table-plugin.scss
This PR includes two adjustments to the `mandatee_table` node:
- Improvements to the serialization: inclusion of css classes for styling and inclusion of the mandatee_table title
- Improvements to the naming of the data-attributes used by the mandatee_table node
- Open the dummy app
- Insert a mandatee table
- Synchronize
- Reload, all attributes of the mandatee table should remain intact
- The styled export should include some css and the title of the mandatee table
This PR is technically breaking, but as the mandatee-table node is not yet deployed anywhere (even not on QA/dev), it does not seem worth it to make a breaking release for this. This PR does not break the API of the plugin.
> Improve `mandatee_table` serialization

- .changeset/honest-geckos-remember.md
- README.md
- ember-cli-build.js
This PR disables fingerprinting on ember-leaflet assets for the test-app. This ensures that the assets are correctly sourced in production builds. For more information, see https://github.com/miguelcobain/ember-leaflet?tab=readme-ov-file#production-builds. 
This PR also includes a section in the README on how to disable fingerprinting in the host app.
[GN-4976](https://binnenland.atlassian.net/browse/GN-4976?atlOrigin=eyJpIjoiMTM5ZjEzZmUzZWFmNDZjYWI3ZTJmZWI5OWI1MmJhN2YiLCJwIjoiaiJ9)
- `pnpm ember build --prod`
- serve the outputted files in dist with a static file server of choice
- Ensure that the map marker is correctly visible
> GN-4976: disable fingerprinting on ember-leaflet assets

- .changeset/spicy-buttons-refuse.md
- app/styles/document-title-plugin.scss
I linked the title annotation to the rdfa-annotations-hover class so it only shows in the actual document and not in any of the exported versions, I see that we removed the rdfa-annotations class so maybe we don't want any of the annotations. In this case we can just remove this code, let me know
GN-4960
Link to frontend
then create a meeting with a besluit in it, see that the title annotation now is not shown in any of the html forms of the agendapoint
As I said we might not want to show this annotation at all
> Only show title annotations in the actual document

- .changeset/modern-cougars-compete.md
- .changeset/old-weeks-swim.md
- addon/plugins/variable-plugin/variables/person.ts
- translations/en-US.yaml
- translations/nl-BE.yaml
Added export to an empty person node to mimic what the user sees in the nodeview. To discuss if this should be like this or we should change both texts (or any of the two at least) to something like "Insert person".
GN-4978
None
Go to the regulatory statements tab, insert a person variable and click on the show raw export button to see that the variable gets correclty exported
As I said maybe we should change the text
> Correctly export empty person nodes

- .changeset/five-rocks-shout.md
- app/styles/article-structure-plugin.scss
This PR consists of some adjustments to the `article-structure-plugin` stylesheet. Specifically, it removes the following two style rules:
```
.rdfa-annotations [property] {
border-bottom-style: none !important;
}
.rdfa-annotations [typeof] {
border-bottom-style: none !important;
}
```
These rules conflict with other style-rules (included in the editor repo) which add a dotted border-bottom to annotated content.
This PR is made as a hotfix on version 19.3.0 (this is the current version of the plugins on GN prod).
[GN-5000](https://binnenland.atlassian.net/browse/GN-5000?atlOrigin=eyJpIjoiOTNkY2JkOTZkZjkzNDhlOThmNDBkMmE0ODEzNDFlMWIiLCJwIjoiaiJ9)
- Open the dummy app
- Insert a decision template
- Ensure that annotated content (like the decision title, description etc.) is marked with a …
> GN-5000: Adjust `article-structure-plugin` stylesheet

- .changeset/cold-schools-heal.md
- addon/components/mandatee-table-plugin/insert.gts
This PR removes the insertion constraint on mandatee tables. This means mandatee tables may be inserted everywhere (including snippets).
None
- Notice that you can insert a mandatee table everywhere in the document (not just in a decision)
- Note: the synchronization of a mandatee table can only be done inside a decision (with the current config).
> mandatee-table plugin: remove insertion constraint on mandatee table insertion

- .changeset/blue-baboons-work.md
- addon/components/decision-plugin/insert-article.gts
- tests/dummy/app/templates/besluit-sample.hbs
This PR introduces an opt-in option to the `insert-article` component to allow for inserting decision articles anywhere in a document (not just to the article-container of a decision). Useful when e.g. creating snippets.
[GN-5009](https://binnenland.atlassian.net/browse/GN-5009)
- Under the `Structures` section, you should find a new `Insert article freely` option
- Using that option, you can insert articles everywhere
- Article number should be correctly recalculated
> GN-5009: add option to insert-article component to allow article insertion anywhere in a document

- .changeset/rude-dogs-fry.md
- addon/plugins/location-plugin/utils/geo-helpers.ts
- addon/plugins/variable-plugin/utils/address-helpers.ts
Noted by @nbittich. I lost the message to reply to, but made a note to fix it.
N/A
N/A
Location plugin still works as before but the RDFa produced works with geosparql tools (I don't know details unfortunately).
N/A
> Fix CRS URI used in location plugin to use correct http: protocol

- .changeset/khaki-ligers-march.md
- addon/plugins/lmb-plugin/utils/fetchMandatees.ts
This PR modifies the approach taken to query the mandatees in the LMB-plugin. It now makes use of the `executeQuery` utility function, which sends a SPARQL query in the `application/x-www-form-urlencoded` format. This also ensures that the service is compatible with any SPARQL endpoint as the plugin now uses a standardized way to send the SPARQL query.
None
You can test this PR with both the current version of the `vendor-proxy` service (0.1.0) or with https://github.com/lblod/vendor-proxy-service/pull/3
You should have a GN stack running containing the `vendor-proxy` service.
The plugin should work as before:
- Open the LMB-mandatee modal
- The correct mandatees should load
Unsure why a custom `json`-based approach was taken to send SPARQL queries. LMK if there is something I missed …
> LMB-plugin: query mandatees using `form-urlencoded` approach

- .changeset/yellow-tables-live.md
- addon/components/lmb-plugin/list.hbs
- addon/components/lmb-plugin/search-modal.hbs
- addon/components/lmb-plugin/search-modal.ts
Discovered that this wasn't wired up when looking into QA feedback.
Related to problems on GN: https://github.com/lblod/app-gelinkt-notuleren/pull/192
And RB: https://github.com/lblod/frontend-reglementaire-bijlage/pull/269
From Jira issue: [binnenland.atlassian.net/browse/GN-5018](https://binnenland.atlassian.net/browse/GN-5018)
Just running the test-app without setting a reasonable endpoint works well as a demonstration of a network error.
Insert a person variable and then insert a person to open the modal.
N/A
> Add error handling to lmb-plugin

- addon/components/besluit-topic-plugin/besluit-topic-toolbar-dropdown.ts
- addon/components/besluit-type-plugin/toolbar-dropdown.ts
- addon/components/citation-plugin/citation-card.ts
- addon/components/citation-plugin/citations/legal-document-detail.ts
- addon/components/citation-plugin/citations/search-modal.ts
- addon/components/lmb-plugin/search-modal.ts
- addon/components/location-plugin/edit.gts
- addon/components/lpdc-plugin/lpdc-modal.ts
- addon/components/roadsign-regulation-plugin/measure-template.ts
- addon/components/snippet-plugin/search-modal.ts
- addon/components/snippet-plugin/snippet-list/snippet-list-modal.ts
- addon/components/variable-plugin/address/edit.ts
- addon/components/variable-plugin/codelist/edit.ts
- addon/components/variable-plugin/codelist/insert.ts
- addon/components/variable-plugin/location/edit.ts
- addon/components/worship-plugin/search-modal.ts
- package.json
Motivation:
- https://majors.nullvoxpopuli.com/q?minors=&old=&packages=ember-resources
- It doesn't feel like enough people have upgraded -- so I made a codemod to help folks get there
Via 
```bash
npx ember-resources-codemod
```
Here is the code for the codemod:
https://github.com/NullVoxPopuli/ember-resources/pull/1147
----------
There aren't many breaking changes from v5 to v7.
Here are the breaking changes in v6:
- https://github.com/NullVoxPopuli/ember-resources/releases/tag/ember-resources%406.0.0
- Of note, the `map` utility (which this library uses) has changed its type signature for better inference)
Here are the breaking changes in v7:
- https://github.com/NullVoxPopuli/ember-resources/releases/tag/v7.0.0-ember-resources
- All utilities moved to `reactiveweb`, documentation …
> npx ember-resources-codemod

- .changeset/gorgeous-taxis-join.md
- addon/components/snippet-plugin/nodes/snippet.gts
- app/styles/snippet-plugin.scss
- tests/dummy/app/controllers/regulatory-statement-sample.ts
On Chrome, clicking the icon de-selected the snippet, which caused the button to disappear and the onClick to never get called. This makes the button transparent instead, which means the onClick still gets called.
Jira ticket: https://binnenland.atlassian.net/browse/GN-5019
GN PR: https://github.com/lblod/frontend-gelinkt-notuleren/pull/716
N/A
Seems to only be easily reproducible in GN/RB and on Chrome. After inserting a snippet, the buttons that appear when the snippet is selected are now functional wherever you click on them. Before clicking on the icon would not work. Moving the selection away from the snippet should hide the buttons.
Seems like weird timing issues and is very hard to debug.
> Make snippet buttons invisible rather than hidden to prevent issues

- .changeset/poor-adults-boil.md
- addon/plugins/template-comments-plugin/node.ts
- package.json
- pnpm-lock.yaml
Uses editor from [the relevant PR](https://github.com/lblod/ember-rdfa-editor/pull/1219), but does not actually depend on it as this would break backwards compatibility.
Editor PR: https://github.com/lblod/ember-rdfa-editor/pull/1219
Jira ticket: [binnenland.atlassian.net/browse/GN-4999](https://binnenland.atlassian.net/browse/GN-4999)
For the second part of the testing, you'll need to link to the PR version of the editor, e.g. by setting the dependency to be `10.5.0-dev.7f01e7e07f7de4b7cef5870bbcffeed2b7589674`
There are two parts to testing this:
1. As-is, the template comment node functions exactly as before.
2. With the PR version of the editor, the new export for publish button in the debug tools shows a version without template comments. The existing export buttons work as before. …
> Hide template comments when publishing

- .changeset/olive-zebras-check.md
- addon/components/snippet-plugin/nodes/snippet.gts
- addon/components/snippet-plugin/snippet-insert-placeholder.gts
- addon/components/snippet-plugin/snippet-insert-rdfa.gts
- addon/components/snippet-plugin/snippet-insert.gts
- addon/components/snippet-plugin/snippet-list-select.gts
- addon/components/snippet-plugin/snippet-list/snippet-list-modal.hbs
- addon/components/snippet-plugin/snippet-list/snippet-list-modal.ts
- addon/plugins/snippet-plugin/commands/insert-snippet.ts
- addon/plugins/snippet-plugin/commands/update-snippet-placeholder.ts
- addon/plugins/snippet-plugin/nodes/snippet-placeholder.ts
- addon/plugins/snippet-plugin/nodes/snippet.ts
- translations/en-US.yaml
- translations/nl-BE.yaml
This PR implements support for configuring a snippet placeholder/snippets to support single/multiple snippets.
[GN-5004](https://binnenland.atlassian.net/browse/GN-5004?atlOrigin=eyJpIjoiZmNlM2YxNjEwMjVjNGViNmEyNzIyMzJmZWFlNDFkOTQiLCJwIjoiaiJ9)
- Open the RB sample page
- Insert a snippet placeholder
**First option**
- Do not enable the checkbox
- Ensure that snippets which are inserted do not have a 'plus' button
- Ensure this persists across reloads
- Ensure this persists when you replace the snippet
**Second option**
- Enable the checkbox
- Inserted snippets should have a 'plus' button
We should/could probably clean-up the components of the snippets a bit. I tried to maintain backwards compatibility.
> GN-5004: add option to enable/disable multi-snippet insertion

- .changeset/yellow-lamps-fly.md
- addon/plugins/citation-plugin/utils/public-decisions.ts
- addon/plugins/citation-plugin/utils/vlaamse-codex.ts
- addon/plugins/snippet-plugin/utils/fetch-data.ts
- addon/services/roadsign-registry.ts
This (draft) PR adjusts the snippet queries to work with the new snippet/snippet-list data-model.
Additionally, it sorts the snippets based on their (custom) position (in ascending order). If such a position is missing (as will be with many older snippets), the snippets are sorted based on their creation-date (in descending order).
If snippets of multiple snippet lists are shown, the sorting works as follows:
- Sort on creation date of the snippet lists (in descending order)
- Then sort on position of the snippets (in ascending order)
- Fallback (if position is missing): sort on creation date of the snippets (in descending order)
[GN-5005](https://binnenland.atlassian.net/browse/GN-5005)
https://github.com/lblod/frontend-reglementaire-bijlage/pull/279 …
> GN-5005: adjust snippet queries to work with new snippet data-model

- addon/components/snippet-plugin/nodes/snippet.gts
- app/styles/snippet-plugin.scss
It seems that we don't actually need to make the buttons invisible if we have `contenteditable="true"`. It looks like the issue is that prosemirror was trying to put the selection into the help text for the buttons. This removes a weird hacky almost-fix that is best not to leave in the codebase to surprise us in the future.
No changeset as it's a purely internal change.
Undoes a hacky part of https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/479
N/A
Needs to be tested in Chrome, with snippets which fill the width of the editor multiple times, e.g. a big block of text.
N/A
> Move back to removing snippet buttons instead of making them invisible

- .changeset/six-ants-appear.md
- addon/components/structure-plugin/_private/structure.gts
- addon/plugins/structure-plugin/node.ts
- addon/plugins/structure-plugin/recalculate-structure-numbers.ts
- translations/en-US.yaml
- translations/nl-BE.yaml
If there's only one article change the title of it and shorten articles from the second one
GN-5002
None
Create a few articles in the besluit part, notice that the numbering still works correctly and when there's only one article left the title changes to "Only article". Also check that the articles from the number 2 are shortened and only shown art. in the title
In the export I hide the number but is still present in the rdfa, this makes sense for me, as any harvesting would like to know that's the article number 1 and also doesn't break any logic based on this, but we would want something else
> Use a special name if you only have one article in the document

- .changeset/cold-bananas-greet.md
- .changeset/stale-peaches-jam.md
- .changeset/violet-cups-dream.md
- addon/components/besluit-topic-plugin/besluit-topic-toolbar-dropdown.ts
- addon/components/besluit-type-plugin/toolbar-dropdown.ts
- addon/components/decision-plugin/decision-plugin-card.gts
- addon/components/decision-plugin/insert-article.gts
- addon/components/lpdc-plugin/lpdc-insert.ts
- addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
- addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
- addon/plugins/besluit-topic-plugin/utils/helpers.ts
- addon/plugins/decision-plugin/commands/insert-article-command.ts
- addon/plugins/decision-plugin/utils/build-article-structure.ts
- addon/plugins/lpdc-plugin/api.ts
- addon/plugins/lpdc-plugin/types.ts
- addon/plugins/roadsign-regulation-plugin/index.ts
- addon/utils/translation.ts
- tests/dummy/app/config/mandatee-table-sample-config.ts
Modified the `decision-plugin`, `lpdc-plugin` and `roadsign-regulation-plugin` to accept the decision uri as config (as well as decision type for roadsigns), to allow for them to be used by vendors without a decision node within the editor. Also refactors any lookups for the decision node so that they use the same util functions.
Jira ticket: https://binnenland.atlassian.net/browse/GN-5104
Embeddable PR: https://github.com/lblod/frontend-embeddable-notule-editor/pull/264
To test you'll need to tweak the sample app to pass the necessary config to the plugins.
- decision-plugin:
- The 'insert freely' functionality works as before (inserts article at the selection)
- Passing a decision uri as config enables the insert button in any context and uses the same behaviour to insert an article …
> Pass decision URI to plugins for if there's no decision node

- .changeset/mighty-mice-itch.md
- addon/plugins/structure-plugin/node.ts
- tests/dummy/app/controllers/besluit-sample.ts
Now the only article attr is also parsed from templates and added it to the templates stored in the test app
GN-5113
None
Insert a template with an article like besluit template and check that it correctly shows enig article 
None
> Parse only article also from templates

- .changeset/eleven-months-know.md
- addon/plugins/structure-plugin/node.ts
Slight correction to how punctuation is handled for single articles.
Makes the output of https://github.com/lblod/frontend-gelinkt-notuleren/pull/749 more sensible.
N/A
Insert a single article and note that there is no longer a ` .` after the title.
N/A
> Do not add `" ."` after only article title

- .changeset/fuzzy-pillows-relax.md
- addon/components/snippet-plugin/nodes/snippet.gts
This PR solves the issue of the snippet buttons' event handlers being fired twice (thus why two snippets were removed at once).
It seems that there were some leftovers of the attempt to resolve the chromium button bug: the button event handlers were tied to both the button and the icon inside it, which results in the handler being fired twice.
[GN-5153](https://binnenland.atlassian.net/browse/GN-5153)
None
**Before**
- Insert two snippets after eachother
- Click on the icon inside the remove button on the first snippet
- Notice that both snippets are removed (due to the event handler being fired twice)
**After**
- Insert two snippets after eachother
- Click on the icon inside the remove button on the first snippet
- Only the relevant snippet should be removed (and …
> GN-5153: only trigger event handlers of snippet actions once

- .changeset/giant-ladybugs-agree.md
- addon/plugins/snippet-plugin/nodes/snippet.ts
- package.json
- pnpm-lock.yaml
- types/lblod/template-uuid-instantiator.d.ts
I found that there were article URIs in GN documents of the form `--ref-uuid4-123-456`. These are from 2 sources, this one is articles within snippets that were not being instantiated correctly. This leads to all snippet users having the same URI for each article within a snippet. There will be another part in GN to insert more normal URIs for new articles, but this is less problematic.
Jira ticket: https://binnenland.atlassian.net/browse/GN-5206
N/A
Insert a snippet including an article and look at the URI for the `besluit:Artikel`.
N/A
> Instantiate template URIs in snippets when inserting

- .changeset/swift-fireants-dress.md
- addon/components/variable-plugin/date/date-time-picker.ts
The date was constructed from the date of today, and then set the day, month and year in that order, if you set the day to a bigger number than the days of the month the day set was wrong, I changed it to do first the year then the month and last the day so this error is no longer possible
GN-5182
None
Insert a date variable then change the date to the 31 of december and notice it correctly works
None
> Fix bug when setting 31/12/.. date

- .changeset/four-eagles-live.md
- .changeset/tough-pugs-shave.md
- addon/components/snippet-plugin/nodes/placeholder.gts
- addon/components/snippet-plugin/nodes/snippet.gts
- addon/components/snippet-plugin/search-modal.hbs
- addon/components/snippet-plugin/search-modal.ts
- addon/components/snippet-plugin/snippet-insert-rdfa.gts
- addon/components/snippet-plugin/snippet-insert.gts
- addon/plugins/snippet-plugin/index.ts
- addon/plugins/snippet-plugin/nodes/snippet-placeholder.ts
- addon/plugins/snippet-plugin/nodes/snippet.ts
- addon/plugins/snippet-plugin/utils/rdfa-predicate.ts
- app/styles/snippet-plugin.scss
- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
- tests/dummy/app/controllers/snippet-edit-sample.ts
- tests/dummy/app/templates/regulatory-statement-sample.hbs
- tests/dummy/app/templates/snippet-edit-sample.hbs
- translations/en-US.yaml
- translations/nl-BE.yaml
Continued a little of the refactoring from replacing the snippet placeholder, so that the snippet placeholder component is now used inside a snippet component. This means that I could re-use the insert logic from the snippet buttons and if we wanted in the future we could include buttons in the same style as for inserted snippets. Since I was not including buttons for now, I was able to use @elpoelma 's redesign implementation work almost untouched.
For consistency, I move the snippet list ids information to RDFa for inserted snippet nodes.
Builds on https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/495
Jira ticket: https://binnenland.atlassian.net/browse/GN-5117
N/A
Insert, replace, delete snippets and snippet placeholders with different configurations and make sure …
> Snippet placeholder redesign

- .changeset/purple-bobcats-lick.md
- README.md
- addon/components/citation-plugin/citation-insert.ts
- addon/plugins/citation-plugin/index.ts
- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
- tests/dummy/app/controllers/snippet-edit-sample.ts
This PR extends/generalizes the 'nodes' config option of the citation plugin.
It now allows you to specify a condition which an active/context node needs to satisfy.
```ts
interface CitationPluginNodeConditionConfig {
type: 'nodes';
regex?: RegExp;
activeInNode(node: PNode, state?: EditorState): boolean;
}
```
The previously expected `activeInNodeTypes` option is marked as deprecated and will be removed in a future release.
Currently, we were still using the  `activeInNodeTypes` option in the dummy app and GN. This failed however, as we do not use the 'motivering' node-spec/type anymore.
[GN-5209](https://binnenland.atlassian.net/browse/GN-5209)
https://github.com/lblod/frontend-gelinkt-notuleren/pull/763
None
- Open the decision sample page
- Insert a decision
- …
> GN-5209: extend/generalize 'nodes' config option to citation plugin

- .changeset/chilled-cooks-juggle.md
- addon/components/mandatee-table-plugin/node.gts
- app/styles/mandatee-table-plugin.scss
- translations/en-US.yaml
- translations/nl-BE.yaml
This PR includes two adjustments to the synchronisation warning shown in mandatee table nodes:
- The message is now clearer/more correct
- The message is now shown in a yellow `AuAlert` component
[GN-5187](https://binnenland.atlassian.net/browse/GN-5187)
None
- Open the 'Besluit sample' page
- Insert a mandatee table
- The sync warning should be clearer in terms of message as well as visibility
> GN-5187: add clearer warning to mandatee table on losing changes

- .changeset/smart-pigs-fly.md
- addon/components/structure-plugin/_private/structure.gts
- app/styles/structure-plugin.scss
This PR removes an unnecessary css rule which showed an alternative type of placeholder in decision articles.
**Before**
https://github.com/user-attachments/assets/49f753eb-7f5f-4c0d-b91d-4bd1d73b2899
**After**
None
- Insert a decision with an article
- Remove the placeholder within the article
- Ensure that no css-placeholder is shown
This was probably a remnant of the article-structures POC where I tried out css placeholders.
> fix(decision-article): remove unnecessary css placeholder

- .changeset/short-pears-deny.md
- addon/plugins/decision-plugin/commands/insert-article-container.ts
This PR fixes an issue where the necessary relationship between the default article and current decision (`eli:has_part`) was not added when inserting an article-container.
None
None
- Open the dummy besluit app
- Insert and empty besluit
- Insert an article-container
- Ensure that the newly created default article is correctly connected to the decision
> bugfix: ensure article-decision relationship when inserting article-container

- .changeset/clean-shoes-repeat.md
- addon/components/besluit-topic-plugin/besluit-topic-toolbar-dropdown.ts
- addon/plugins/besluit-topic-plugin/commands/update-besluit-topic-resource.ts
Supports the old predicate but migrates away from it on any change.
Jira ticket: https://binnenland.atlassian.net/browse/GN-5021
N/A
Set up a decision before applying the change to make sure you test backwards compatibility. Setting or unsetting themes should work as expected.
N/A
> Change decision theme to use dct:subject in place of eli:is_about

- .changeset/young-eagles-exist.md
- addon/plugins/decision-plugin/commands/insert-article-container.ts
This PR ensures that the `recalculateNumbers` transaction-monad is executed when inserting an article container.
None
None
- Insert an empty decision without an article block
**Scenario 1**
- Insert an article block
- Ensure that the default article shows 'Only article'
**Scenario 2**
- Insert an article freely
- Then insert an article block
- The article numbering should be correct
> Fix: recalculate article numbers when inserting article container

- .changeset/few-buses-pay.md
- .changeset/five-suits-pull.md
- .changeset/wicked-berries-sing.md
- addon/components/location-plugin/insert.gts
- addon/plugins/location-plugin/node-contents/address.ts
- addon/plugins/location-plugin/node-contents/area.ts
- addon/plugins/location-plugin/node-contents/place.ts
- addon/plugins/location-plugin/node.ts
- addon/plugins/location-plugin/utils/node-utils.ts
- tests/dummy/app/controllers/besluit-sample.ts
- tests/dummy/app/controllers/regulatory-statement-sample.ts
- tests/dummy/app/controllers/snippet-edit-sample.ts
- tests/dummy/app/templates/regulatory-statement-sample.hbs
Also move from dct:spatial to prov:atLocation.
I spent some time refactoring the address variable to re-use a load of the code from the oslo location node and so to benefit from these changes, but I realised that substantially increases the scope of the changes. Instead of finishing those changes, I've not committed them. If we think we should include them, I'll add them, otherwise I'll hold on to them for now.
The links are made in RDFa but only the backlink works in the RDFa tools. This is unfixed as we need to refactor how these nodes work anyway, so should do this then.
Edit: In order to avoid a weird situation of having 2 `prov:atLocation` triples with different objects for each location, I included a more substantial refactor which 'de-variable-ifies' the location code. So, now:
- …
> Add ability to link locations with the wider document automatically

- .changeset/popular-countries-listen.md
- addon/components/citation-plugin/citation-card.ts
- addon/components/citation-plugin/citations/legal-document-detail.ts
- addon/plugins/citation-plugin/index.ts
- pnpm-lock.yaml
- tests/dummy/app/templates/besluit-sample.hbs
Convert the citation plugin into a keyed one, so we don't have to pass it as an argument to the citation card, and makes it easier to configure the frontend
https://github.com/lblod/frontend-gelinkt-notuleren/pull/792
None
Check the citation plugin is working as it should
None
> Convert citation into a keyed plugin

- .changeset/fluffy-carrots-drum.md
- addon/components/snippet-plugin/nodes/snippet.gts
- app/styles/snippet-plugin.scss
Redesigned fragment nodes according to the new design 
GN-5120
None
Insert a snippet, and check that the design of it is the same as in the figma attached to the issue 
Nobody was here so I must have missed something on the design, but didn't see anything more. Also might need to check with saska because I had to recreate the badge which I don't really like
> Redesign of fragment nodes

- .changeset/short-walls-sparkle.md
- addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
- addon/plugins/roadsign-regulation-plugin/index.ts
This PR deprecates the mistyped  `articleUriGenrator` in favour for `articleUriGenerator` option in the roadsign-regulation plugin.
> roadsign-regulation plugin: deprecate `articleUriGenrator` in favour for `articleUriGenerator` option

- .changeset/hot-mugs-decide.md
- addon/plugins/snippet-plugin/nodes/snippet.ts
- addon/plugins/variable-plugin/variables/autofilled.ts
- addon/plugins/variable-plugin/variables/text.ts
This PR includes some adjustments to the attribute serializations of the following nodespecs:
- `autofilled` variable
- `snippet` node
- `text` variable
These nodespecs incorrectly serialized all their attributes (including non-legal HTML attributes).
None
- Start the app
- Ensure that the `autofilled`, `text` and `snippet` nodes still serialize + parse correctly
> bugfix: cleanup incorrect attribute serializations

- .changeset/hot-comics-act.md
- addon/components/location-plugin/edit.gts
- addon/plugins/location-plugin/node-contents/address.ts
- addon/plugins/location-plugin/utils/address-helpers.ts
- addon/utils/namespace.ts
- translations/en-US.yaml
- translations/nl-BE.yaml
This PR includes support for inserting truncated addresses.
A truncated address is an address without the zipcode and municipality name shown. These attributes are still encoded in hidden RDFa.
[GN-4881](https://binnenland.atlassian.net/browse/GN-4881?atlOrigin=eyJpIjoiNGFhYzAwNDUwMGI2NGVlY2FlNzgyOTBkMGJhZGRjMDAiLCJwIjoiaiJ9)
None
- Click on the 'Insert location' sidebar button
- While filling in an address, ensure that you can select whether or not it should be inserted in a 'truncated' format
- Ensure the truncated/non-truncated address format is persisted across document reloads
> GN-4881: support for truncated addresses

- .changeset/sharp-parents-eat.md
- addon/components/structure-plugin/_private/structure.gts
- app/styles/structure-plugin.scss
- pnpm-lock.yaml
Makes clicking in titles work better by leveraging flex rendering to make the title box as wide as the whole header
also removes the margin from the content, which came from a rule somewhere in the editor stylings. I used important here to get around it, which is not ideal but it works.
This prevents the state where clicking in just the wrong spot node-selects the structure (characterized by having no blinking cursor), after which typing would replace the whole structure with the typed text.
Another way to prevent this would have been making the structure no longer node-selectable, but that then interferes with how we likely want the backspace into the structure nodes to behave.
built on #535
> fix(structures): add css solution to fix title behavior

- .changeset/blue-suns-guess.md
- .changeset/smooth-insects-pull.md
- addon/components/structure-plugin/_private/control-card.gts
- addon/plugins/article-structure-plugin/commands/insert-structure.ts
- addon/plugins/article-structure-plugin/utils/structure.ts
- addon/plugins/decision-plugin/utils/build-article-structure.ts
- addon/plugins/structure-plugin/insert-structure.ts
- addon/plugins/structure-plugin/move-structure.ts
- addon/plugins/structure-plugin/node.ts
- addon/plugins/structure-plugin/recalculate-structure-numbers.ts
- addon/plugins/structure-plugin/regenerate-rdfa-links.ts
- addon/plugins/structure-plugin/structure-types.ts
- package.json
- pnpm-lock.yaml
- tests/dummy/app/controllers/regulatory-statement-sample.ts
- tests/dummy/app/templates/regulatory-statement-sample.hbs
- translations/en-US.yaml
- translations/nl-BE.yaml
The structure plugin code for this was generic enough that this was easy, just needed some tweaking and translations. ~~Still need to include the 'start number' functionality to replace the article structure card.~~
For reviewing, I recommend the 'hide whitespace changes' option.
Part of https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/535
Jira ticket: [binnenland.atlassian.net/browse/GN-4866](https://binnenland.atlassian.net/browse/GN-4866)
N/A
The card to move and remove structures in the RS part of the dummy app should work as expected.
Setting start numbers should work as expected.
N/A
> Add support for moving and numbering structures to structure plugin

- addon/components/structure-plugin/_private/structure.gts
This PR passes an empty string to the `embedded` title editor in case the structure title is `null`.
- Open the RB page
- Insert some structures
- Ensure that no errors show up related to the structure title being `null`
> fix: handle case where structure title is `null`

- .changeset/poor-walls-flash.md
- addon/plugins/roadsign-regulation-plugin/queries/sign-codes.ts
- addon/utils/sparql-helpers.ts
This PR fixes the functionality of the 'code' dropdown/filter in the IRGN plugin.
The plugin now uses the native `xsd:boolean` type in the SPARQL queries.
https://github.com/lblod/app-mow-registry/pull/112
- Insert a decision with type 'reglement'
- Open the IRGN modal
- Notice you can correctly filter on the code of a measure
> fix(irgn): fix functionality of code dropdown

- .changeset/red-ghosts-listen.md
- addon/components/structure-plugin/_private/structure.gts
- addon/utils/_private/transaction-utils.ts
This PR ensures that structure title changes which quickly succeed eachother are composed using the `composition` transaction meta.
If `prosemirror-history` encounters successive transactions with the same `composition` ID, it bundles them together into one event. 
While this `composition` meta is part of the internal API, it seems to be the best way to compose successive transactions as one history event.
Internally, prosemirror uses the `composition` ID in combination with the [compositionstart](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionstart_event) and [compositionend](https://developer.mozilla.org/en-US/docs/Web/API/Element/compositionend_event) events.
- Open the RS page
- Insert any structure with an editable title
- Apply some changes …
> Use `composition` to compose quick successive structure title changes

- .changeset/fair-months-invent.md
- addon/components/location-plugin/edit.gts
- addon/components/location-plugin/insert.gts
- addon/components/location-plugin/map.gts
- tests/dummy/app/templates/besluit-sample.hbs
This PR adds support for configuring the location types shown by the location plugin.
The location types may be configured through the `@locationTypes` argument of the `location-plugin/insert` component.
The `@locationTypes` argument expects an array of `LocationType` values.
Supported `LocationType` values are:
- 'address'
- 'place'
- 'area'
By default the value of `@locationTypes` is `['address', 'place', 'area']`
[GN-5468](https://binnenland.atlassian.net/browse/GN-5468)
- Open the 'insert location' modal
- Notice that the order of the tabs has changed (in correspondence with the config inside the dummy app)
- If you adjust the `@locationTypes` argument, the modal should update accordingly
- Passing and unsupported location type causes an error.
> GN-5468: add support for configuring location types

- .changeset/breezy-dodos-press.md
- .changeset/chilly-hounds-jog.md
- addon/components/table-of-contents-plugin/ember-nodes/outline.hbs
- addon/components/table-of-contents-plugin/ember-nodes/table-of-contents.hbs
- addon/components/table-of-contents-plugin/ember-nodes/table-of-contents.ts
- addon/plugins/structure-plugin/node.ts
- addon/plugins/table-of-contents-plugin/index.ts
- addon/plugins/table-of-contents-plugin/nodes/table-of-contents.ts
- addon/plugins/table-of-contents-plugin/utils/index.ts
- package.json
- pnpm-lock.yaml
- tests/dummy/app/controllers/regulatory-statement-sample.ts
BREAKING: this bumps the peerdeps of ember-appuniversum and ember-concurrency to the ranges the editor needs. 
- the config is no longer required. Instead, the ToC looks at the `tocEntry` property of a nodeSpec. This makes the ToC logic way simpler and decouples it from the implementation of hierarchies and other complexities
- Passing in the legacy config, an array, will active the legacy mode. So the behavior will not change until you change the config.
- passing in an object (not an array) with a `scrollContainer` callback is now also supported, but it is entirely optional as the plugin will try to find its scrollcontainer on its own.
https://binnenland.atlassian.net/browse/GN-5387
go to the regulatory statement sample page, add some structures, add the ToC.
Observe it automatically …
> Rework ToC to be compatible with new structure nodes

- .changeset/metal-glasses-reply.md
- addon/components/common/documents/preview.gts
- addon/components/common/documents/types.ts
- addon/components/snippet-plugin/nodes/snippet.gts
- addon/components/snippet-plugin/snippet-insert.gts
- addon/plugins/snippet-plugin/index.ts
- addon/plugins/snippet-plugin/utils/collate-imported-resources.ts
- translations/en-US.yaml
- translations/nl-BE.yaml
I managed to forget that I was hacking around the async nature of the template previews, so the version I'd put in a PR for didn't actually work for what I needed. I also missed some translations referring to snippets the first time around.
Part of https://binnenland.atlassian.net/browse/GN-5418
N/A
Snippets should just work, but they don't use the async behaviour. To test async, you can replace the implementation of `Snippet` in `plugins/snippet-plugin/index.ts` with:
```
export class Snippet implements PreviewableDocument {
_content: string | null;
createdOn: string | null;
title: string | null;
constructor({ title, createdOn, content }: SnippetArgs) {
this._content = content;
this.createdOn = dateValue(createdOn ?? undefined);
this.title = title;
}
get content() {
console.log(
'Getting …
```
> Add support for async content in PreviewList previews

- .changeset/cold-stingrays-design.md
- translations/en-US.yaml
- translations/nl-BE.yaml
Changed the `to`to `to and including` in the number variable modal as the max number is also allowed
GN-5481
None
Insert a number variable and notice the text is updated
None
> Change number variable modal to clarify the upper number is also included in the range

- .changeset/pretty-turkeys-vanish.md
- translations/nl-BE.yaml
As title says :)
GN-4785
None
Launch the editor in dutch, notice it now says citaat where it should
None
> Rename "citeeropschrift" to "citaat"

- .changeset/hot-hats-wink.md
- addon/components/location-plugin/map.gts
- app/styles/location-plugin.scss
- index.js
- types/ember-leaflet.d.ts
While in ember-leaflet the default icons are used as PNGs, in leaflet they are actually SVGs, so just use that in a 'DivIcon'.
Also tweak the cursor to be a 'pointer' so we can actually see where we're clicking for points/areas.
Part of https://binnenland.atlassian.net/browse/GN-5507
N/A
The location plugin should just work, for all location types. The points selected should be where the pointer is when clicking and should match the vertices of area polygons.
Some things that seem broken from ember-leaflet.
> Use inline SVG for location plugin markers instead of the default icon

- .changeset/itchy-coats-nail.md
- addon/plugins/variable-plugin/variables/number.ts
[GN-5539](https://binnenland.atlassian.net/browse/GN-5539)
Not 100% sure all old variables will get parsed into a state where they use rdf:value
I checked the parserules and it seems so, though the "modern" one just takes the rdfa attributes verbatim so there's a slight chance it could get it wrong, but I don't think so
> Use correct rdf:value instead of ext:content when serializing

- .changeset/grumpy-clocks-jam.md
- addon/components/variable-plugin/location/edit.hbs
- app/styles/variable-plugin.scss
Long story short, the powerselect was miscalculating the position of the dropdown, and producing a bug where the option got selected on mouseup, this should solve the miscalculation by fixing the width of the dropdown even when it's not displayed
GN-5479
None
Make your window small so the options of a location have to be displayed in 2 rows, then scroll the sidebar so the powerselect dropdown needs to be displayed above the powerselect, notice that the bug doesn't happen anymore and the dropdown is displayed in the correct position
Breakpoints are always kinda ugly but don't know a better solution
> Solved bug with powerselect dropdown not displaying in place

- .changeset/rare-meals-jam.md
- addon/plugins/roadsign-regulation-plugin/nodes.ts
- package.json
- pnpm-lock.yaml
This PR adds a backward-compatible parserule to the `roadsign_regulation` nodespec which converts classic `roadsign_regulation` nodes to `block_rdfa` nodes in the best of its capabilities.
None
- Start the test-app and open the decision sample page
- Find an (older) 'reglement' decision on GN, which contains a classic `roadsign_regulation` node
- Copy the decision and paste it in the test-app
- Ensure the `roadsign_regulation` node has been converted to a `block_rdfa` node and contains the necessary RDFa properties and relationships.
- Adding the parserule to the `roadsign_regulation` spec itself is not ideal. I'd prefer using some kind of 'loose' parserule. It feels a bit silly to just add a nodespec just for its parserule...
- Unsure if we should mark this as breaking
- Hopefully the …
> feat: add backward-compatible parserule to `roadsign_regulation`  nodespec

- .changeset/lazy-spies-peel.md
- addon/models/electee.ts
- addon/plugins/besluit-type-plugin/utils/fetchBesluitTypes.ts
- package.json
- pnpm-lock.yaml
This PR removes obsolete `fetch-sparql-endpoint` dependency. This dependency requires node.js polyfills, which we are no longer providing with this package. This caused an issue in some applications using the `besluit-type` plugin.
- Use this package in https://github.com/lblod/frontend-gelinkt-notuleren
- Ensure the `besluit-type` plugin behaves as expected
> fix(besluit-type-plugin): remove fetch-sparql-endpoint dep

- .changeset/rotten-trainers-allow.md
- addon/components/citation-plugin/citations/search-modal.ts
Removes the unsupported `keyboardInstruction` property from `AuDatePicker` `localization` argument
- Start the test-app
- Open an 'Insert citation' modal instance
- Ensure no error pops-up in the console on the unsupported `keyboardInstruction` property
> fix(citation-plugin): remove usage of unsupported `keyboardInstruction` argument

- .changeset/dry-eggs-fly.md
- addon/plugins/structure-plugin/node.ts
Add the eli:title property back to the structures so the rdfa is correct
maybe CIT-27
None
Add a structure node, check that the html exported contains the eli:title property and the content is correct
None
> Add eli:title properties to structure nodes

- .changeset/poor-jokes-dance.md
- addon/components/_private/appuniversum-overrides/au-card.gts
- addon/components/variable-plugin/date/edit.hbs
- addon/components/variable-plugin/date/edit.ts
This PR introduces a custom (temporary) `AuCard` component which does not make use of the `AuContent` component.
This fixes the styling issues of the date-variable date-picker while still allowing apps to use the latest appuniversum version.
- Install `ember-appuniversum` version 3.6 or later
- Open the test-app
- Insert a date and select it
- Open the date-picker and ensure it is styled correctly
> fix(date-variable): fix date picker styling

- .changeset/sharp-turkeys-greet.md
- addon/plugins/location-plugin/utils/geo-helpers.ts
Needed for Virtuoso to accept area locations as valid when enabling geosparql support.
Jira ticket: https://binnenland.atlassian.net/browse/CIT-61
No set-up needed to test that the location plugin still works, but to check that harvesting works correctly, follow the instructions in [the plugins PR for changing to rdf:HTML datatype](https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/579) for how to do this. Instead of using the app-lblod-harvester version pointed to in that PR, use the `feature/citerra` branch. A GN frontend using this PR is also needed: `32.1.0-dev.57d72b6f4f4d02524f5e6e7e1256c11f3ee026d4`.
Looking at plugin output directly:
- In the test app, insert an area location and look at the HTML output. The `asWKT` predicate should be pointing to a `wktLiteral` string, …
> Ensure location plugin outputs WKT polygons with matching start and end

- .changeset/early-jobs-joke.md
- addon/components/roadsign-regulation-plugin/roadsigns-modal.gts
The function for searching the sign by code in the roadsign regulation plugin was sending the label of the category instead of the uri so the filter was failing
GN-5640
None
Open the roadsign regulation plugin and check that you can now filter by a category and then search for signs in that category
None
> Category filter was not working on roadsign regulation plugin

- .changeset/hip-steaks-dance.md
- addon/components/roadsign-regulation-plugin/expanded-measure.gts
- addon/plugins/roadsign-regulation-plugin/queries/mobility-measure-concept.ts
This PR fixes the issue where it was not possible to mark measure as having variable/dynamic signalization before inserting them in the document.
[GN-5646](https://binnenland.atlassian.net/browse/GN-5646?atlOrigin=eyJpIjoiNzllOWE3OWViNzllNGRmOWI5NTI0ZmM0MDIyOWVmYmYiLCJwIjoiaiJ9)
Connect the roadsign-regulation-plugin to MOW QA
- Start the test-app
- Insert a regulation and open the insert-measure modal
- Search for a measure which supports variable signalization
- Ensure you can now select between a 'variable'/'non-variable' option
Whether or not the masure is temporal is not encoded in RDFa, but only in text 'Deze signalisatie is dynamish'. We might also want to encode the selected value in RDFa?
> GN-5646: roadsign-regulation-plugin - fix variable signage feature

- .changeset/fast-ladybugs-admire.md
- .changeset/late-radios-joke.md
- addon/components/roadsign-regulation-plugin/roadsigns-modal.gts
- addon/plugins/roadsign-regulation-plugin/queries/mobility-measure-concept.ts
When fixing the categories I didn't notice that the types were also broken, they should be fixed now, I also tested all the parts of the modal and they are working. So please also test them so we don't miss anything :)
GN-5686
None
Test that you can filter on type of traffic measure and then you get signs related to that type, also check that everything else works in the modal 
None
> Fix traffic measure type filter

- .changeset/nervous-baboons-call.md
- addon/components/roadsign-regulation-plugin/roadsigns-table.gts
- addon/plugins/roadsign-regulation-plugin/queries/traffic-signal-concept.ts
Move the image part of the query into an optional and handle the resulting undefined images. In order to display something to the user, I put just the code of the sign in a pill.
Jira ticket: https://binnenland.atlassian.net/browse/GN-5681
Works well if pointing to QA as it avoids the need to produce your own (broken) test data.
Inserting signs with no images (such as `WM72.2` on QA, generates the correct text mentioning the signs as well as the template (see ticket).
N/A
> Fix inserted text to include traffic signals without images

- .changeset/eight-tips-obey.md
- addon/plugins/roadsign-regulation-plugin/queries/mobility-measure-concept.ts
- addon/plugins/roadsign-regulation-plugin/queries/traffic-signal-concept.ts
- addon/plugins/roadsign-regulation-plugin/schemas/traffic-signal-concept.ts
This PR adjusts the roadsign-regulation-plugin to ensure traffic signals belonging to a mobility measure are correctly ordered based on their position.
This PR also keeps the previous behaviour intact, in case the plugin is connected to a MOW backend which does not yet contain the new list-item/position data for the road signals.
https://binnenland.atlassian.net/browse/GN-5739?atlOrigin=eyJpIjoiYWYzNjYxNTM2NTQwNDMzNDk5MDM3ODE0Njc0NzhhZmUiLCJwIjoiaiJ9
Connect to the `/raw-sparql` endpoint of the MOW registry you are using, to see changes in the order of signals be directly reflected.
Ideally, this PR should be tested with both a MOW backend containing the position-data, and one which doesn't contain any position-data.
- Create a regulation decision
- Open the traffic measure modal
- Ensure …
> GN-5739: order traffic signals based on position

- .changeset/old-squids-flash.md
- addon/components/roadsign-regulation-plugin/expanded-measure.gts
- addon/components/roadsign-regulation-plugin/roadsigns-modal.gts
- addon/plugins/roadsign-regulation-plugin/actions/insert-measure.ts
- addon/plugins/roadsign-regulation-plugin/constants.ts
Updates the text content to reflect whether the measure is zonal (and so if those signs are being applied to that zone).
Jira ticket: https://binnenland.atlassian.net/browse/GN-5722
N/A
- Insert a zonal measure and note the extra text after signs and sub-signs
- Insert a non-zonal measure and note there is no additional text
- Repeat the same with a potentially-zonal measure and selecting zonal or not
Understanding what Zonal means...
> Add text indicating zonality to newly inserted zonal measures
