lblod/ember-rdfa-editor-lblod-plugins

addon/components/roadsign-regulation-plugin/roadsigns-modal.ts
Solves https://binnenland.atlassian.net/browse/GN-3954?atlOrigin=eyJpIjoiYjI2NmE5ZTk5YWFhNDFmZThkZTg5ZDQyMjM4ODAyNzkiLCJwIjoiaiJ9.
=> Add space before 'met zonale geldigheid'

addon/components/besluit-type-plugin/toolbar-dropdown.hbs, addon/components/besluit-type-plugin/toolbar-dropdown.ts, package-lock.json, package.json
Ensures that the besluit-type pill is loaded with the correct besluit after a reload/save.
Solves https://binnenland.atlassian.net/browse/GN-3975?atlOrigin=eyJpIjoiYzViNTk2Nzg3MTVhNDkyZmI4OGEzZjZmMDBlNGVlODYiLCJwIjoiaiJ9.
=> Update besluit-type pill after having fetched the besluit types

addon/components/roadsign-regulation-plugin/roadsign-regulation-card.hbs, addon/components/roadsign-regulation-plugin/roadsign-regulation-card.ts
Solves https://binnenland.atlassian.net/jira/software/c/projects/GN/boards/4?modal=detail&selectedIssue=GN-3970.
=> Ensure new roadsign regulations are scrolled into view after insertion

CHANGELOG.md, translations/nl-BE.yaml
Solution to https://binnenland.atlassian.net/browse/GN-3991?atlOrigin=eyJpIjoiMjY5NmI4ZGE5YzExNDkwOTg2YzcyNWYzOTYyNjcwMmUiLCJwIjoiaiJ9
=> Fix subsection 'move down' dutch translation

addon/components/rdfa-date-plugin/insert.hbs, addon/components/rdfa-date-plugin/insert.ts
Not sure which label should I put in this, I added the bug one but feel free to change it if you think another one is more suited
=> Remove insert date and time as it's no longer needed

addon/plugins/article-structure-plugin/structures/article-paragraph.ts, addon/plugins/article-structure-plugin/structures/article.ts, addon/plugins/article-structure-plugin/structures/structure-header.ts, addon/plugins/standard-template-plugin/utils/nodes.ts
Solves some parts of https://binnenland.atlassian.net/browse/GN-3992?atlOrigin=eyJpIjoiOTNiYTZhY2NmZTE5NDg1Njk5NWQxMjQ0MDY4Yjc2ZGEiLCJwIjoiaiJ9.
=> Set selectable on false for structure-headers

CHANGELOG.md, addon/plugins/article-structure-plugin/structures/article-paragraph.ts
Not sure if this was a misscomunication, but it's a simple fix thanks to the structure spec we developed :)
=> Article paragraphs should not be numbered continuous

CHANGELOG.md, addon/plugins/article-structure-plugin/structures/article-paragraph.ts, tests/dummy/app/controllers/regulatory-statement-sample.ts
Changed paragraph symbol to solve https://binnenland.atlassian.net/browse/GN-4163 and updated the schema to be on sync with the new changes to reglementaire billage
=> change paragraph symbol and updated schema on dummy page

CHANGELOG.md, addon/components/article-structure-plugin/structure-card.hbs
Currently it's not possible to add the padding as a class directly to the component, so I suggested a change on the appuniversum repo. I see they also want to get rid of this component and create a new one, so this will need changed anyway in the future
=> add padding to structure card

CHANGELOG.md, addon/components/rdfa-date-plugin/card.ts, addon/components/variable-plugin/insert-variable-card.hbs, addon/plugins/variable-plugin/utils/constants.ts
https://user-images.githubusercontent.com/769698/226565039-2d33dee4-07a7-4c9b-a4e3-c15ff5dee1f1.mp4
It inserts date with a placeholder, but I don't like that there is a "now" date in the date input in the right sidebar :( I took a stab at it, but it looks like a bigger change, so I will do that as a separate ticket if that is fine?
=> GN-4176: Placeholder text when inserting date

CHANGELOG.md, addon/components/article-structure-plugin/structure-card.hbs, addon/components/article-structure-plugin/structure-card.ts, addon/components/hover-tooltip.hbs, addon/components/hover-tooltip.ts, addon/plugins/article-structure-plugin/index.ts, addon/plugins/article-structure-plugin/structures/article-paragraph.ts, addon/plugins/article-structure-plugin/structures/article.ts, addon/plugins/article-structure-plugin/structures/chapter.ts, addon/plugins/article-structure-plugin/structures/section.ts, addon/plugins/article-structure-plugin/structures/subsection.ts, addon/plugins/article-structure-plugin/structures/title.ts, app/components/hover-tooltip.js, tests/dummy/app/routes/application.ts, translations/en-US.yaml, translations/nl-BE.yaml
- feat(component): add a hover-tooltip utility component
- fix(i18n): properly initialize ember-intl in the dummy app
- feat(structures): separate the remove card into buttons, and add new translations
fixes https://binnenland.atlassian.net/browse/GN-4202
=> Explain the removal options for structures

CHANGELOG.md, addon/components/rdfa-date-plugin/date.hbs, addon/components/rdfa-date-plugin/date.ts, addon/components/variable-plugin/insert-variable-card.hbs, addon/components/variable-plugin/insert-variable-card.ts, addon/components/variable-plugin/template-variable-card.hbs, addon/components/variable-plugin/template-variable-card.ts, addon/components/variable-plugin/variable.hbs, addon/components/variable-plugin/variable.ts, addon/plugins/rdfa-date-plugin/nodes/date.ts, addon/plugins/variable-plugin/nodes.ts, addon/plugins/variable-plugin/utils/constants.ts, app/components/rdfa-date-plugin/date.js, app/styles/variable-plugin.scss, package-lock.json, package.json, tests/dummy/app/controllers/besluit-sample.ts, tests/dummy/app/controllers/regulatory-statement-sample.ts, translations/en-US.yaml, translations/nl-BE.yaml
https://binnenland.atlassian.net/browse/GN-4298
=> add label to variables

CHANGELOG.md, addon/components/citation-plugin/citations/article-preview.hbs, addon/components/citation-plugin/helpers/alert-load-error.hbs, addon/components/citation-plugin/helpers/alert-no-items.hbs, addon/plugins/citation-plugin/utils/vlaamse-codex.ts, tests/dummy/app/templates/besluit-sample.hbs, translations/nl-BE.yaml
started by looking into that weird `htmlsafe` import, but also found a bunch of small problems
- fix(i18n): fix typo
- fix(citation): add missing argument to citation card in dummy app
- fix(citation): remove the unnecessary type and add the html-safe tag at the rendering site
- fix(citation): correct erroneous arguments to AuAlert
relates to #159 
citations without articles now show a proper message instead of an empty square
the citation sidebar card actually works now on the dummy app
=> small citation plugin fixes 

CHANGELOG.md, package-lock.json, package.json
=> Update typescript to 5.0.4

CHANGELOG.md, package-lock.json, package.json
=> Bump date fns to 2.30

CHANGELOG.md, README.md
This PR adds an entry on the article-structure plugin in the README. It documents how the widgets should be added, and adds an explanation on how the plugin can be configured.
Jira: https://binnenland.atlassian.net/browse/GN-4273?atlOrigin=eyJpIjoiZGE2N2VmZjZkMzI1NDFkYTg1YzBjOGI3OGRjZDM0YWUiLCJwIjoiaiJ9
=> GN-4273: article-structure plugin documentation

CHANGELOG.md, README.md
Adds needed import statement for template comments + some small typo fixes in the rest of the readme.
https://binnenland.atlassian.net/browse/GN-4461
Note: templateNodes is not a thing anymore and hence is not added to the readme.
read the readme :)
=> Update readme: small fixes and imports for template comments

CHANGELOG.md, addon/plugins/article-structure-plugin/commands/wrap-structure-content.ts
Be smarter about how we approach attempt to wrap structured nodes. More comments in the code.
https://binnenland.atlassian.net/browse/GN-4425
1. Checkout
2. `npm run start` 
3. Go to [Regulatory Statement Sample](http://localhost:4200/regulatory-statement-sample)
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/assets/769698/172d8c23-f316-4eae-bf22-b2ee94c574f1
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/assets/769698/5516b3de-9c8c-4856-a9ed-18b465c9a9d4
=> GN-4425: Smarter content wrapping

CHANGELOG.md, package-lock.json, package.json
This PR updates the `@lblod/ember-rdfa-editor` package from 5.2.0 to 5.3.0.
=> Update editor from 5.2.0 to 5.3.0

.changeset/stupid-cameras-lie.md, addon/helpers/capitalize.ts, addon/helpers/in-array.ts, addon/helpers/limit-text.ts, app/components/citation-plugin/citations/modal.js, app/components/template-comments-plugin/comment-editor.js, app/components/template-comments-plugin/insert-template-comment.js, app/services/rdfa-editor-roadsign-regulation-plugin.js
Small tweaks to more correctly handle imports and exports from dummy-app code in order to support embroider builds.
PR based on #323 as that is also needed for embroider builds, so it doesn't make sense to separate this.
N/A
Everything should just work as before...
N/A
=> Support embroider builds

addon/components/snippet-plugin/snippet-insert.ts, addon/components/variable-plugin/codelist/insert.ts, addon/plugins/article-structure-plugin/structures/article-paragraph.ts, addon/plugins/variable-plugin/variables/date.ts, addon/plugins/variable-plugin/variables/number.ts, addon/plugins/variable-plugin/variables/text.ts, app/styles/article-structure-plugin.scss
See commit history for details. Couple of fixes for parsing and general node attribute bookkeeping,
and a bit of a UI overhaul for the structures to make them usable in a real document.
npm link the rdfa branch of the editor
Development was done while linked to the RB frontend futurenow branch, so things may not look
as good in the dummy app.
=> Various parsing and UX fixes

.changeset/sour-zebras-carry.md, addon/components/template-comments-plugin/template-comment.ts, addon/plugins/template-comments-plugin/node.ts, translations/en-US.yaml, translations/nl-BE.yaml
cherry pick the changes from https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/386
=> simplify label of template comments

.changeset/great-lions-behave.md
=> GN-4802: RDFa changeset

.changeset/nine-jars-compete.md, translations/nl-BE.yaml
=> GN-4692: Add missing translation for decision plugin

tests/dummy/app/controllers/besluit-sample.ts, tests/dummy/app/templates/besluit-sample.hbs
Minor fix just for the test environment, at some point in the merges of the branch GN-4876 the changes of the besluit sample didn't got merged, basically this fixes it and now the insert person from lmb button in the sidebar correctly works.
I guess we don't need changelog or anything for this as is just relevant for our testing environment, but correct me if I'm wrong
=> Insert person was broken on the besluit sample page

.changeset/mean-donkeys-sip.md, tests/dummy/app/controllers/besluit-sample.ts
Added body to templates so they can be inserted
None
None
Insert a template from the sidebar and check that it works
=> Added body to templates

.changeset/mighty-waves-obey.md, addon/components/lmb-plugin/list.hbs, addon/components/lmb-plugin/search-modal.hbs, addon/components/lmb-plugin/search-modal.ts, addon/plugins/lmb-plugin/index.ts, addon/plugins/lmb-plugin/utils/fetchMandatees.ts, addon/utils/constants.ts, tests/dummy/app/controllers/besluit-sample.ts, tests/dummy/app/templates/besluit-sample.hbs, translations/en-US.yaml, translations/nl-BE.yaml
- fix the bugs with the query
- add filter on admin period
- add filter on admin unit
[GN-5201](https://binnenland.atlassian.net/browse/GN-5201)
=> Improve LMB plugin

.changeset/twenty-mugs-fail.md, package.json, pnpm-lock.yaml
Updates `@lblod/template-uuid-instantiator` to https://github.com/lblod/template-uuid-instantiator/pull/2
https://github.com/lblod/template-uuid-instantiator/pull/2
=> update template-uuid-instantiator to 1.0.3

.changeset/hip-buttons-behave.md, app/styles/mandatee-table-plugin.scss, app/styles/snippet-plugin.scss, package.json, pnpm-lock.yaml
In rounding the selection of snippet placeholders, found some other ember nodes with inconsistent rounding, so rounded them instead of adding more overrides for rounded selections.
Draft until the editor PR is merged.
Uses https://github.com/lblod/ember-rdfa-editor/pull/1235
N/A
Check all nodes have a consistent border-radius and the selection box matches this.
There is a weird crash in some templates in RS-sample, I'll look into it in a separate PR...
=> Consistently round corners of Ember nodes

.changeset/hip-worms-hug.md, addon/components/structure-plugin/_private/structure.gts, addon/plugins/article-structure-plugin/commands/insert-structure.ts, addon/utils/nested-prosemirror.ts
Fixes 4 bugs:
- case where dom state and editor state could diverge (see https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/535#issuecomment-2656482078)
- fixes spurious undo entries when inserting a structure
- fixes spurious undo entries when editing a title
- adds ctrl-z/y keymap to the nested header editor
=> Fix structure rendering and history bugs

.changeset/friendly-suits-deliver.md, translations/en-US.yaml, translations/nl-BE.yaml
Improve the title of the structure card. Even if the issue didn't say it I also changed the english version to be in line with the dutch one
GN-5536
None
Just go to the RB sample and check that the title on the structure card is changed 
None
=> Improve title of structure card

.changeset/khaki-seals-tease.md, addon/components/hover-tooltip.gts, addon/components/variable-plugin/date/edit.hbs, addon/components/variable-plugin/number/nodeview.hbs
This PR adjusts the positioning strategy used in `ember-velcro` components from `fixed` to `absolute`.
This ensures that these velcro popups are still correctly positioned when the editor is used inside an embedded application in e.g. a shadow-root, without needing to revert to certain CSS hacks.
**In this repo**
- Open the test-app
- Ensure all popups/dropdowns are still correctly positioned
=> fix(velcro): use absolute positioning

.changeset/rotten-olives-agree.md, addon/plugins/roadsign-regulation-plugin/queries/mobility-measure-concept.ts
Page by page, rather than by 1...
N/A
N/A
Pagination works as expected for inserting traffic measures.
N/A
=> Fix pagination of roadsign-regulation modal
